-- JSB assessment: load this submission's 30 tables into MySQL 8 / MariaDB 10.x.
-- Generated by local_load/build_load_sql.py.
-- WARNING: re-running DROPS and reloads these 30 tables. Any rows added or changed in them
-- since the last load are lost. Tables not created by this script are never touched.
-- MySQL Workbench: File > Open SQL Script, then Execute (lightning bolt).
-- Command line (XAMPP): C:\xampp\mysql\bin\mysql.exe -u root < 01_load_submission_tables.sql
SET NAMES utf8mb4;

-- ===================== Exercise 3 =====================
-- Exercise 3: Database design for players, wallets, bets and bonuses
-- Tool: MySQL 8.0 / MariaDB 10.11 (InnoDB, utf8mb4). 24 tables.
--
-- Design principles (justified in design_notes.md):
--   * Money: DECIMAL(18,4) everywhere. Never FLOAT/DOUBLE for anything that touches a balance.
--   * Time: DATETIME(6), always UTC, named *_at_utc where ambiguity is possible. TIMESTAMP is
--     avoided because MySQL silently converts it using the session/server time zone, which is
--     exactly the kind of silent, hard-to-audit behaviour a finance-grade schema should not have.
--   * PII lives only in player_identity, separated from behavioural/analytical data (players).
--   * The wallet ledger (wallet_transactions) is append-only and is the only source of truth for
--     balances; wallets.*_balance is a materialised, recomputable cache, never edited directly.
--   * History that must be provable at a point in time (VIP tier, tags, account status and KYC)
--     uses SCD Type 2, not UPDATE-in-place.
--   * CHECK constraints hold the rules a row must obey on its own (positive amounts, a ledger row's
--     balance_after = balance_before +/- amount, a reversal points at what it reverses). Rules that
--     span rows are enforced by the posting procedures in ledger_posting.sql.
--   * One header table (bets) plus one detail table per product, so a sports leg, a casino round
--     and a retail slip are not forced into one over-wide table (see design_notes.md, "grain").

CREATE DATABASE IF NOT EXISTS jsb_platform CHARACTER SET utf8mb4;
USE jsb_platform;

SET FOREIGN_KEY_CHECKS = 0;

-- ===========================================================================
-- PLAYERS
-- ===========================================================================
DROP TABLE IF EXISTS affiliates;
CREATE TABLE affiliates (
    affiliate_id    INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    affiliate_code  VARCHAR(30)     NOT NULL UNIQUE,
    name            VARCHAR(120)    NOT NULL,
    traffic_source  VARCHAR(50)     NOT NULL,   -- e.g. 'organic', 'affiliate', 'referral', 'retail_walk_in'
    created_at_utc  DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS players;
CREATE TABLE players (
    player_id       BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    -- Behavioural / operational attributes only. No name, DOB, ID number, address here.
    registered_at_utc DATETIME(6)   NOT NULL,
    registration_channel ENUM('web','app','retail') NOT NULL,
    kyc_status      ENUM('not_started','pending','verified','rejected') NOT NULL DEFAULT 'not_started',
    vip_tier        VARCHAR(20)     NOT NULL DEFAULT 'standard',  -- current value; history in player_vip_tier_history
    status          ENUM('active','blocked','self_excluded','closed') NOT NULL DEFAULT 'active',  -- current; history in player_status_history
    status_reason   VARCHAR(255)    NULL,
    traffic_source  VARCHAR(50)     NOT NULL,
    affiliate_id    INT UNSIGNED    NULL,
    preferred_currency CHAR(3)      NOT NULL DEFAULT 'NAD',
    created_at_utc  DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at_utc  DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_players_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliates(affiliate_id),
    KEY ix_players_status (status),
    KEY ix_players_vip_tier (vip_tier)
) ENGINE=InnoDB;

-- Restricted tier: PII lives here only. In production: column-level encryption
-- (e.g. AES at the application layer, or MySQL column encryption via a KMS-backed
-- key) on id_number/dob/address, a dedicated low-privilege DB user for this table
-- only, and every SELECT against it logged (see design_notes.md).
DROP TABLE IF EXISTS player_identity;
CREATE TABLE player_identity (
    player_id       BIGINT UNSIGNED PRIMARY KEY,
    first_name      VARCHAR(100)    NOT NULL,
    last_name       VARCHAR(100)    NOT NULL,
    date_of_birth   DATE            NOT NULL,
    national_id_number VARBINARY(255) NOT NULL,   -- application-layer encrypted
    email           VARCHAR(255)    NOT NULL,
    phone           VARCHAR(30)     NOT NULL,
    address_line1   VARCHAR(255)    NULL,
    address_city    VARCHAR(100)    NULL,
    address_country CHAR(2)         NOT NULL,     -- ISO 3166-1 alpha-2
    updated_at_utc  DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_identity_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    UNIQUE KEY uq_identity_email (email)
) ENGINE=InnoDB;

-- SCD2: VIP tier history. players.vip_tier is the current value (fast to read);
-- this table is what "what was the tier on 3 June" queries against.
DROP TABLE IF EXISTS player_vip_tier_history;
CREATE TABLE player_vip_tier_history (
    player_id       BIGINT UNSIGNED NOT NULL,
    vip_tier        VARCHAR(20)     NOT NULL,
    valid_from_utc  DATETIME(6)     NOT NULL,
    valid_to_utc    DATETIME(6)     NULL,          -- NULL = current
    changed_by      VARCHAR(100)    NOT NULL,       -- system rule name or staff user
    PRIMARY KEY (player_id, valid_from_utc),
    CONSTRAINT fk_viphist_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT ck_viphist_period CHECK (valid_to_utc IS NULL OR valid_to_utc > valid_from_utc),
    KEY ix_viphist_current (player_id, valid_to_utc)
) ENGINE=InnoDB;

-- SCD2: account status and KYC status. Regulators ask "was this player self-excluded (or
-- unverified) when the bet was placed?", so the current value on players is not enough.
DROP TABLE IF EXISTS player_status_history;
CREATE TABLE player_status_history (
    player_id       BIGINT UNSIGNED NOT NULL,
    status          ENUM('active','blocked','self_excluded','closed') NOT NULL,
    kyc_status      ENUM('not_started','pending','verified','rejected') NOT NULL,
    reason          VARCHAR(255)    NULL,           -- e.g. self-exclusion period, reason for a block
    valid_from_utc  DATETIME(6)     NOT NULL,
    valid_to_utc    DATETIME(6)     NULL,           -- NULL = current
    changed_by      VARCHAR(100)    NOT NULL,
    PRIMARY KEY (player_id, valid_from_utc),
    CONSTRAINT fk_statushist_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT ck_statushist_period CHECK (valid_to_utc IS NULL OR valid_to_utc > valid_from_utc),
    KEY ix_statushist_current (player_id, valid_to_utc)
) ENGINE=InnoDB;

-- SCD2: tags (multi-valued, e.g. 'bonus_abuse_watch', 'high_value', 'self_excluded_nudge').
DROP TABLE IF EXISTS player_tag_history;
CREATE TABLE player_tag_history (
    tag_history_id  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player_id       BIGINT UNSIGNED NOT NULL,
    tag             VARCHAR(50)     NOT NULL,
    valid_from_utc  DATETIME(6)     NOT NULL,
    valid_to_utc    DATETIME(6)     NULL,
    CONSTRAINT fk_taghist_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT ck_taghist_period CHECK (valid_to_utc IS NULL OR valid_to_utc > valid_from_utc),
    UNIQUE KEY uq_taghist_start (player_id, tag, valid_from_utc),
    KEY ix_taghist_current (player_id, tag, valid_to_utc)
) ENGINE=InnoDB;

-- ===========================================================================
-- WALLETS & THE LEDGER
-- ===========================================================================
DROP TABLE IF EXISTS wallets;
CREATE TABLE wallets (
    wallet_id       BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player_id       BIGINT UNSIGNED NOT NULL,
    currency        CHAR(3)         NOT NULL DEFAULT 'NAD',
    -- Materialised cache of wallet_transactions, recomputable at any time.
    -- Never written directly by application code -- only by the ledger-posting
    -- procedure, in the same transaction as the ledger row (see design_notes.md).
    real_balance    DECIMAL(18,4)   NOT NULL DEFAULT 0,
    bonus_balance   DECIMAL(18,4)   NOT NULL DEFAULT 0,
    updated_at_utc  DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_wallet_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    UNIQUE KEY uq_wallet_player_currency (player_id, currency),
    CONSTRAINT ck_wallet_nonneg CHECK (real_balance >= 0 AND bonus_balance >= 0)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS wallet_transactions;
CREATE TABLE wallet_transactions (
    wallet_txn_id   BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    wallet_id       BIGINT UNSIGNED NOT NULL,
    player_id       BIGINT UNSIGNED NOT NULL,       -- denormalised for query convenience; always = wallets.player_id
    txn_type        ENUM('deposit','withdrawal','bet_stake','bet_win','bonus_credit',
                         'bonus_debit','refund','reversal','manual_adjustment') NOT NULL,
    balance_type    ENUM('real','bonus')            NOT NULL,
    amount          DECIMAL(18,4)   NOT NULL,        -- always positive; sign is implied by txn_type
    direction       ENUM('credit','debit')          NOT NULL,
    balance_before  DECIMAL(18,4)   NOT NULL,
    balance_after   DECIMAL(18,4)   NOT NULL,
    -- Lineage back to the event that caused this movement: at most one is set
    -- (ck_wtxn_one_source). A manual adjustment has none and carries a reason instead.
    related_deposit_attempt_id BIGINT UNSIGNED NULL,
    related_withdrawal_id      BIGINT UNSIGNED NULL,
    related_bet_id             BIGINT UNSIGNED NULL,
    related_player_bonus_id    BIGINT UNSIGNED NULL,
    reversal_of_wallet_txn_id  BIGINT UNSIGNED NULL,  -- set only on a 'reversal' row: the row it cancels
    reason          VARCHAR(255)    NULL,            -- required for manual adjustments and reversals
    created_by      VARCHAR(100)    NOT NULL DEFAULT 'system',  -- service or staff user that posted it
    -- Deterministic idempotency key: source_system + source_event_id (or a hash
    -- of immutable business fields for internally-generated events). Loads are
    -- upserts against this key -- replaying an event is always safe.
    idempotency_key VARCHAR(150)    NOT NULL,
    source_system   VARCHAR(30)     NOT NULL DEFAULT 'platform',
    -- No status column: a row is never updated. "Reversed" is derived: another row points at it.
    created_at_utc  DATETIME(6)     NOT NULL,
    ingested_at_utc DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_wtxn_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id),
    CONSTRAINT fk_wtxn_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT fk_wtxn_reversal FOREIGN KEY (reversal_of_wallet_txn_id) REFERENCES wallet_transactions(wallet_txn_id),
    CONSTRAINT ck_wtxn_amount_pos CHECK (amount > 0),
    CONSTRAINT ck_wtxn_balance_math CHECK (balance_after = balance_before + CASE WHEN direction = 'credit' THEN amount ELSE -amount END),
    CONSTRAINT ck_wtxn_reversal_link CHECK ((txn_type = 'reversal' AND reversal_of_wallet_txn_id IS NOT NULL) OR (txn_type <> 'reversal' AND reversal_of_wallet_txn_id IS NULL)),
    CONSTRAINT ck_wtxn_one_source CHECK (CASE WHEN related_deposit_attempt_id IS NULL THEN 0 ELSE 1 END + CASE WHEN related_withdrawal_id IS NULL THEN 0 ELSE 1 END + CASE WHEN related_bet_id IS NULL THEN 0 ELSE 1 END + CASE WHEN related_player_bonus_id IS NULL THEN 0 ELSE 1 END + CASE WHEN reversal_of_wallet_txn_id IS NULL THEN 0 ELSE 1 END <= 1),
    CONSTRAINT ck_wtxn_reason CHECK (txn_type NOT IN ('manual_adjustment','reversal') OR reason IS NOT NULL),
    UNIQUE KEY uq_wtxn_idempotency (idempotency_key),
    UNIQUE KEY uq_wtxn_reversal_of (reversal_of_wallet_txn_id),   -- a row can be reversed once only
    KEY ix_wtxn_wallet_time (wallet_id, created_at_utc),
    KEY ix_wtxn_player_time (player_id, created_at_utc),
    KEY ix_wtxn_bet (related_bet_id),
    KEY ix_wtxn_bonus (related_player_bonus_id)
) ENGINE=InnoDB;

-- ===========================================================================
-- PAYMENTS (feeds the wallet ledger; also what Exercise 1's reconciliation reads)
-- ===========================================================================
DROP TABLE IF EXISTS payment_methods;
CREATE TABLE payment_methods (
    method_id       INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    method_code     VARCHAR(30)     NOT NULL UNIQUE,   -- e.g. 'EFT_INSTANT', 'VOUCHER', 'MOBILE_MONEY'
    rail_family     VARCHAR(30)     NOT NULL           -- e.g. 'EFT', 'card', 'voucher', 'mobile_money'
) ENGINE=InnoDB;

DROP TABLE IF EXISTS deposit_attempts;
CREATE TABLE deposit_attempts (
    deposit_attempt_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player_id       BIGINT UNSIGNED NOT NULL,
    method_id       INT UNSIGNED    NOT NULL,
    amount          DECIMAL(18,4)   NOT NULL,
    currency        CHAR(3)         NOT NULL,
    gateway_ref     VARCHAR(50)     NOT NULL,
    status          ENUM('initiated','success','failed') NOT NULL,
    created_at_utc  DATETIME(6)     NOT NULL,
    settled_at_utc  DATETIME(6)     NULL,
    CONSTRAINT fk_deposit_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT fk_deposit_method FOREIGN KEY (method_id) REFERENCES payment_methods(method_id),
    CONSTRAINT ck_deposit_amount_pos CHECK (amount > 0),
    KEY ix_deposit_player_time (player_id, created_at_utc),
    UNIQUE KEY uq_deposit_gateway_ref (gateway_ref)   -- one attempt per gateway reference (Ex 1 found duplicates without this)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS withdrawal_requests;
CREATE TABLE withdrawal_requests (
    withdrawal_id   BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id      VARCHAR(64)     NOT NULL,   -- client idempotency key
    player_id       BIGINT UNSIGNED NOT NULL,
    method_id       INT UNSIGNED    NOT NULL,
    amount          DECIMAL(18,4)   NOT NULL,
    currency        CHAR(3)         NOT NULL,
    status          ENUM('requested','approved','paid','failed','cancelled') NOT NULL,
    requested_at_utc DATETIME(6)    NOT NULL,
    paid_at_utc     DATETIME(6)     NULL,
    CONSTRAINT fk_withdrawal_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT fk_withdrawal_method FOREIGN KEY (method_id) REFERENCES payment_methods(method_id),
    CONSTRAINT ck_withdrawal_amount_pos CHECK (amount > 0),
    UNIQUE KEY uq_withdrawal_request (request_id),
    KEY ix_withdrawal_player_time (player_id, requested_at_utc)
) ENGINE=InnoDB;

-- ===========================================================================
-- BETS: one header, one detail table per product (see "grain" in design_notes.md)
-- ===========================================================================
DROP TABLE IF EXISTS bets;
CREATE TABLE bets (
    bet_id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id      VARCHAR(64)     NOT NULL,   -- client idempotency key: a retried bet request can't create a second bet
    player_id       BIGINT UNSIGNED NOT NULL,
    product         ENUM('sportsbook','casino','retail') NOT NULL,
    channel         ENUM('web','app','retail') NOT NULL,
    stake_real_amount  DECIMAL(18,4) NOT NULL DEFAULT 0,
    stake_bonus_amount DECIMAL(18,4) NOT NULL DEFAULT 0,
    total_stake     DECIMAL(18,4)   GENERATED ALWAYS AS (stake_real_amount + stake_bonus_amount) STORED,
    player_bonus_id BIGINT UNSIGNED NULL,       -- the grant whose bonus balance paid stake_bonus_amount
    status          ENUM('open','won','lost','void','cashed_out') NOT NULL DEFAULT 'open',
    payout_amount   DECIMAL(18,4)   NOT NULL DEFAULT 0,
    placed_at_utc   DATETIME(6)     NOT NULL,
    settled_at_utc  DATETIME(6)     NULL,
    CONSTRAINT fk_bets_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT ck_bets_stake_nonneg CHECK (stake_real_amount >= 0 AND stake_bonus_amount >= 0),
    CONSTRAINT ck_bets_stake_positive CHECK (stake_real_amount + stake_bonus_amount > 0),
    CONSTRAINT ck_bets_bonus_funding CHECK ((stake_bonus_amount = 0 AND player_bonus_id IS NULL) OR (stake_bonus_amount > 0 AND player_bonus_id IS NOT NULL)),
    CONSTRAINT ck_bets_payout_nonneg CHECK (payout_amount >= 0),
    CONSTRAINT ck_bets_settled_time CHECK (status = 'open' OR settled_at_utc IS NOT NULL),
    UNIQUE KEY uq_bets_request (request_id),
    KEY ix_bets_player_time (player_id, placed_at_utc),
    KEY ix_bets_product_time (product, placed_at_utc, status),
    KEY ix_bets_product_settled (product, settled_at_utc),   -- NGR by month is cut on settlement
    KEY ix_bets_player_bonus (player_bonus_id)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS sports_events;
CREATE TABLE sports_events (
    event_id        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sport            VARCHAR(50)    NOT NULL,
    league           VARCHAR(100)   NOT NULL,
    home_team        VARCHAR(100)   NOT NULL,
    away_team        VARCHAR(100)   NOT NULL,
    starts_at_utc    DATETIME(6)    NOT NULL,
    UNIQUE KEY uq_event_fixture (sport, league, home_team, away_team, starts_at_utc)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS sports_bet_details;
CREATE TABLE sports_bet_details (
    bet_id          BIGINT UNSIGNED PRIMARY KEY,
    bet_class       ENUM('single','accumulator') NOT NULL,
    total_odds      DECIMAL(10,3)   NOT NULL,
    leg_count       SMALLINT UNSIGNED NOT NULL,
    min_odds_rule_applied DECIMAL(10,3) NULL,  -- captured for bonus-rollover audit (min odds rule)
    CONSTRAINT fk_sportsdet_bet FOREIGN KEY (bet_id) REFERENCES bets(bet_id),
    CONSTRAINT ck_sportsdet_legs CHECK ((bet_class = 'single' AND leg_count = 1) OR (bet_class = 'accumulator' AND leg_count >= 2))
) ENGINE=InnoDB;

DROP TABLE IF EXISTS bet_legs;
CREATE TABLE bet_legs (
    leg_id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    bet_id          BIGINT UNSIGNED NOT NULL,
    event_id        BIGINT UNSIGNED NOT NULL,
    market          VARCHAR(100)    NOT NULL,   -- e.g. 'match_winner', 'over_under_2.5'
    selection       VARCHAR(100)    NOT NULL,
    odds            DECIMAL(10,3)   NOT NULL,
    leg_result      ENUM('pending','won','lost','void') NOT NULL DEFAULT 'pending',
    CONSTRAINT fk_leg_bet FOREIGN KEY (bet_id) REFERENCES bets(bet_id),
    CONSTRAINT fk_leg_event FOREIGN KEY (event_id) REFERENCES sports_events(event_id),
    CONSTRAINT ck_leg_odds CHECK (odds > 1),
    UNIQUE KEY uq_leg_bet_event_market (bet_id, event_id, market)   -- also serves bet_id lookups
) ENGINE=InnoDB;

DROP TABLE IF EXISTS game_providers;
CREATE TABLE game_providers (
    provider_id     INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL UNIQUE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS games;
CREATE TABLE games (
    game_id         INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    provider_id     INT UNSIGNED    NOT NULL,
    name            VARCHAR(150)    NOT NULL,
    category        VARCHAR(50)     NOT NULL,   -- 'slots','table','live_dealer',...
    rtp_theoretical DECIMAL(6,3)    NOT NULL,   -- % as configured by the provider
    CONSTRAINT fk_games_provider FOREIGN KEY (provider_id) REFERENCES game_providers(provider_id),
    UNIQUE KEY uq_game_provider_name (provider_id, name)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS casino_round_details;
CREATE TABLE casino_round_details (
    bet_id          BIGINT UNSIGNED PRIMARY KEY,
    game_id         INT UNSIGNED    NOT NULL,
    provider_round_ref VARCHAR(100) NOT NULL,   -- provider's own round id, for their-side reconciliation
    CONSTRAINT fk_casinodet_bet FOREIGN KEY (bet_id) REFERENCES bets(bet_id),
    CONSTRAINT fk_casinodet_game FOREIGN KEY (game_id) REFERENCES games(game_id),
    UNIQUE KEY uq_casino_provider_round (game_id, provider_round_ref)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS retail_locations;
CREATE TABLE retail_locations (
    location_id     INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(150)    NOT NULL,
    address_city    VARCHAR(100)    NOT NULL,
    UNIQUE KEY uq_location_name_city (name, address_city)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS devices;
CREATE TABLE devices (
    device_id       BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fingerprint     VARCHAR(255)    NOT NULL UNIQUE,
    device_type     VARCHAR(30)     NOT NULL   -- 'pos_terminal','mobile','desktop'
) ENGINE=InnoDB;

DROP TABLE IF EXISTS retail_bet_details;
CREATE TABLE retail_bet_details (
    bet_id          BIGINT UNSIGNED PRIMARY KEY,
    location_id     INT UNSIGNED    NOT NULL,
    device_id       BIGINT UNSIGNED NOT NULL,
    ticket_number   VARCHAR(50)     NOT NULL,
    CONSTRAINT fk_retaildet_bet FOREIGN KEY (bet_id) REFERENCES bets(bet_id),
    CONSTRAINT fk_retaildet_loc FOREIGN KEY (location_id) REFERENCES retail_locations(location_id),
    CONSTRAINT fk_retaildet_device FOREIGN KEY (device_id) REFERENCES devices(device_id),
    UNIQUE KEY uq_retail_ticket (location_id, ticket_number)
) ENGINE=InnoDB;

-- ===========================================================================
-- BONUSES
-- ===========================================================================
DROP TABLE IF EXISTS bonus_campaigns;
CREATE TABLE bonus_campaigns (
    campaign_id     INT UNSIGNED    AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(150)    NOT NULL,
    campaign_type   ENUM('registration','deposit_match','cashback','free_spins','other') NOT NULL,
    trigger_rule    VARCHAR(255)    NOT NULL,       -- e.g. 'first_deposit', 'weekly_net_loss>0'
    audience_rule   VARCHAR(255)    NOT NULL,       -- e.g. 'all', 'vip_tier=gold'
    rollover_multiple DECIMAL(6,2)  NOT NULL,
    min_odds        DECIMAL(10,3)   NULL,
    max_stake_while_active DECIMAL(18,4) NULL,
    expiry_days     INT UNSIGNED    NOT NULL,
    valid_from_utc  DATETIME(6)     NOT NULL,
    valid_to_utc    DATETIME(6)     NULL,
    terms_json      JSON            NULL,
    CONSTRAINT ck_campaign_rollover CHECK (rollover_multiple >= 0),
    UNIQUE KEY uq_campaign_name_from (name, valid_from_utc)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS player_bonuses;
CREATE TABLE player_bonuses (
    player_bonus_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player_id       BIGINT UNSIGNED NOT NULL,
    campaign_id     INT UNSIGNED    NOT NULL,
    granted_amount  DECIMAL(18,4)   NOT NULL,
    rollover_required DECIMAL(18,4) NOT NULL,        -- granted_amount * campaign.rollover_multiple at grant time
    rollover_progress DECIMAL(18,4) NOT NULL DEFAULT 0,  -- cache; recomputable from bonus_rollover_events
    status          ENUM('active','completed','expired','forfeited') NOT NULL DEFAULT 'active',
    granted_at_utc  DATETIME(6)     NOT NULL,
    expires_at_utc  DATETIME(6)     NOT NULL,
    resolved_at_utc DATETIME(6)     NULL,
    CONSTRAINT fk_pbonus_player FOREIGN KEY (player_id) REFERENCES players(player_id),
    CONSTRAINT fk_pbonus_campaign FOREIGN KEY (campaign_id) REFERENCES bonus_campaigns(campaign_id),
    CONSTRAINT ck_pbonus_amount_pos CHECK (granted_amount > 0),
    CONSTRAINT ck_pbonus_resolved CHECK ((status = 'active' AND resolved_at_utc IS NULL) OR (status <> 'active' AND resolved_at_utc IS NOT NULL)),
    CONSTRAINT ck_pbonus_expiry CHECK (expires_at_utc > granted_at_utc),
    KEY ix_pbonus_player_status (player_id, status)
) ENGINE=InnoDB;

-- Every qualifying bet's contribution to rollover, event-sourced so
-- rollover_progress above is always recomputable and auditable, never just a
-- trusted running counter.
DROP TABLE IF EXISTS bonus_rollover_events;
CREATE TABLE bonus_rollover_events (
    rollover_event_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    player_bonus_id BIGINT UNSIGNED NOT NULL,
    bet_id          BIGINT UNSIGNED NOT NULL,
    contribution_amount DECIMAL(18,4) NOT NULL,
    created_at_utc  DATETIME(6)     NOT NULL,
    CONSTRAINT fk_rollover_pbonus FOREIGN KEY (player_bonus_id) REFERENCES player_bonuses(player_bonus_id),
    CONSTRAINT fk_rollover_bet FOREIGN KEY (bet_id) REFERENCES bets(bet_id),
    UNIQUE KEY uq_rollover_bet_bonus (player_bonus_id, bet_id)
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS = 1;

-- Now that wallet_transactions exists, wire the FKs that were forward references.
ALTER TABLE wallet_transactions
    ADD CONSTRAINT fk_wtxn_deposit FOREIGN KEY (related_deposit_attempt_id) REFERENCES deposit_attempts(deposit_attempt_id),
    ADD CONSTRAINT fk_wtxn_withdrawal FOREIGN KEY (related_withdrawal_id) REFERENCES withdrawal_requests(withdrawal_id),
    ADD CONSTRAINT fk_wtxn_bet FOREIGN KEY (related_bet_id) REFERENCES bets(bet_id),
    ADD CONSTRAINT fk_wtxn_bonus FOREIGN KEY (related_player_bonus_id) REFERENCES player_bonuses(player_bonus_id);

ALTER TABLE bets
    ADD CONSTRAINT fk_bets_player_bonus FOREIGN KEY (player_bonus_id) REFERENCES player_bonuses(player_bonus_id);

USE jsb_platform;
-- Minimal seed data so example_queries.sql returns real, checkable results.
-- Not a volume test -- just enough of each entity to exercise every relationship.
USE jsb_platform;

INSERT INTO affiliates (affiliate_id, affiliate_code, name, traffic_source) VALUES
  (1,'AFF-001','Windhoek Sports Blog','affiliate'),
  (2,'AFF-002','Direct','organic');

INSERT INTO players (player_id, registered_at_utc, registration_channel, kyc_status, vip_tier, status, traffic_source, affiliate_id, preferred_currency) VALUES
  (1,'2026-08-01 08:00:00','web','verified','gold','active','affiliate',1,'NAD'),
  (2,'2026-08-15 09:30:00','retail','verified','standard','active','organic',2,'NAD'),
  (3,'2026-08-20 12:00:00','app','verified','standard','active','organic',2,'NAD');

INSERT INTO player_identity (player_id, first_name, last_name, date_of_birth, national_id_number, email, phone, address_city, address_country) VALUES
  (1,'Anna','Shikongo','1990-04-12', 'ENC[demo-only]', 'anna.s@example.com','+264811000001','Windhoek','NA'),
  (2,'Johan','Beukes','1985-11-03', 'ENC[demo-only]', 'johan.b@example.com','+264811000002','Windhoek','NA'),
  (3,'Maria','Nangolo','1992-02-27','ENC[demo-only]', 'maria.n@example.com','+264811000003','Swakopmund','NA');

INSERT INTO player_vip_tier_history (player_id, vip_tier, valid_from_utc, valid_to_utc, changed_by) VALUES
  (1,'standard','2026-08-01 08:00:00','2026-09-01 00:00:00','system:tier_rule'),
  (1,'gold','2026-09-01 00:00:00',NULL,'system:tier_rule'),
  (2,'standard','2026-08-15 09:30:00',NULL,'system:tier_rule'),
  (3,'standard','2026-08-20 12:00:00',NULL,'system:tier_rule');

-- Status and KYC over time: player 1 registered unverified and passed KYC the next day.
INSERT INTO player_status_history (player_id, status, kyc_status, reason, valid_from_utc, valid_to_utc, changed_by) VALUES
  (1,'active','pending',NULL,'2026-08-01 08:00:00','2026-08-02 10:00:00','system:registration'),
  (1,'active','verified','KYC documents approved','2026-08-02 10:00:00',NULL,'kyc_team:agent_014'),
  (2,'active','verified',NULL,'2026-08-15 09:30:00',NULL,'system:registration'),
  (3,'active','verified',NULL,'2026-08-20 12:00:00',NULL,'system:registration');

INSERT INTO player_tag_history (player_id, tag, valid_from_utc, valid_to_utc) VALUES
  (1,'high_value','2026-09-01 00:00:00',NULL),
  (3,'bonus_abuse_watch','2026-09-05 00:00:00',NULL);

-- Cache values equal the ledger totals of the wallet_transactions below; the
-- dbt test assert_wallet_cache_matches_ledger fails the build if they drift.
INSERT INTO wallets (wallet_id, player_id, currency, real_balance, bonus_balance) VALUES
  (1,1,'NAD', 890.00, 0.00),
  (2,2,'NAD', 415.00, 0.00),
  (3,3,'NAD', 90.00, 10.00);

INSERT INTO payment_methods (method_id, method_code, rail_family) VALUES
  (1,'EFT_INSTANT','EFT'), (2,'VOUCHER','voucher');

-- Query (d) fixture: player 2 fails once, then succeeds shortly after.
INSERT INTO deposit_attempts (deposit_attempt_id, player_id, method_id, amount, currency, gateway_ref, status, created_at_utc, settled_at_utc) VALUES
  (1,2,1,500.00,'NAD','GW-D0001','failed','2026-09-10 09:00:00',NULL),
  (2,2,1,500.00,'NAD','GW-D0002','success','2026-09-10 09:04:00','2026-09-10 09:05:00'),
  (3,1,1,1000.00,'NAD','GW-D0003','success','2026-09-02 10:00:00','2026-09-02 10:01:00'),
  (4,3,1,100.00,'NAD','GW-D0004','success','2026-09-03 11:00:00','2026-09-03 11:01:00');

INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_deposit_attempt_id, idempotency_key, created_at_utc)
VALUES
  (1,2,2,'deposit','real',500.00,'credit',0,500.00,2,'deposit:GW-D0002','2026-09-10 09:05:00'),
  (2,1,1,'deposit','real',1000.00,'credit',0,1000.00,3,'deposit:GW-D0003','2026-09-02 10:01:00'),
  (3,3,3,'deposit','real',100.00,'credit',0,100.00,4,'deposit:GW-D0004','2026-09-03 11:01:00');

-- Bonus: registration bonus for player 3 (active, partly wagered) and for player 2 (forfeited
-- unwagered when they withdrew before meeting the rollover: removed from the bonus balance, so it cost nothing).
INSERT INTO bonus_campaigns (campaign_id, name, campaign_type, trigger_rule, audience_rule, rollover_multiple, min_odds, expiry_days, valid_from_utc) VALUES
  (1,'Registration Bonus','registration','first_deposit','all_new_players',3.00,1.500,30,'2026-01-01 00:00:00');

INSERT INTO player_bonuses (player_bonus_id, player_id, campaign_id, granted_amount, rollover_required, rollover_progress, status, granted_at_utc, expires_at_utc, resolved_at_utc) VALUES
  (1,3,1,50.00,150.00,50.00,'active','2026-09-03 11:05:00','2026-10-03 11:05:00',NULL),
  (2,2,1,25.00,75.00,0.00,'forfeited','2026-09-15 09:05:00','2026-10-15 09:05:00','2026-09-20 10:00:00');

INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_player_bonus_id, idempotency_key, created_at_utc)
VALUES
  (4,3,3,'bonus_credit','bonus',50.00,'credit',0,50.00,1,'bonus_grant:1','2026-09-03 11:05:00');

-- Sportsbook: player 1 places a single, wins.
INSERT INTO sports_events (event_id, sport, league, home_team, away_team, starts_at_utc) VALUES
  (1,'Football','Namibia Premier League','Blue Waters','African Stars','2026-09-05 15:00:00');

-- Bet 2 is paid entirely from player 3's bonus balance (grant 1); bets can also split real + bonus.
INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, player_bonus_id, status, payout_amount, placed_at_utc, settled_at_utc) VALUES
  (1,'REQ-BET-0001',1,'sportsbook','web',200.00,0.00,NULL,'won',360.00,'2026-09-05 14:00:00','2026-09-05 17:00:00'),
  (2,'REQ-BET-0002',3,'sportsbook','app',0.00,20.00,1,'lost',0.00,'2026-09-06 10:00:00','2026-09-06 12:00:00');

INSERT INTO sports_bet_details (bet_id, bet_class, total_odds, leg_count, min_odds_rule_applied) VALUES
  (1,'single',1.800,1,NULL),
  (2,'single',2.000,1,1.500);

INSERT INTO bet_legs (bet_id, event_id, market, selection, odds, leg_result) VALUES
  (1,1,'match_winner','Blue Waters',1.800,'won'),
  (2,1,'match_winner','African Stars',2.000,'lost');

INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc)
VALUES
  (5,1,1,'bet_stake','real',200.00,'debit',1000.00,800.00,1,'bet_stake:1','2026-09-05 14:00:00'),
  (6,1,1,'bet_win','real',360.00,'credit',800.00,1160.00,1,'bet_win:1','2026-09-05 17:00:00'),
  (7,3,3,'bet_stake','bonus',20.00,'debit',50.00,30.00,2,'bet_stake:2','2026-09-06 10:00:00');

INSERT INTO bonus_rollover_events (player_bonus_id, bet_id, contribution_amount, created_at_utc) VALUES
  (1,2,20.00,'2026-09-06 12:00:00');

-- Casino: player 1 plays a round.
INSERT INTO game_providers (provider_id, name) VALUES (1,'Pragmatic Play');
INSERT INTO games (game_id, provider_id, name, category, rtp_theoretical) VALUES (1,1,'Gates of Olympus','slots',96.500);
INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, status, payout_amount, placed_at_utc, settled_at_utc) VALUES
  (3,'REQ-BET-0003',1,'casino','app',50.00,0.00,'won',80.00,'2026-09-07 20:00:00','2026-09-07 20:00:05');
INSERT INTO casino_round_details (bet_id, game_id, provider_round_ref) VALUES (3,1,'PP-ROUND-000123');
INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc)
VALUES
  (8,1,1,'bet_stake','real',50.00,'debit',1160.00,1110.00,3,'bet_stake:3','2026-09-07 20:00:00'),
  (9,1,1,'bet_win','real',80.00,'credit',1110.00,1190.00,3,'bet_win:3','2026-09-07 20:00:05');

-- Retail: player 2 places a bet at a location.
INSERT INTO retail_locations (location_id, name, address_city) VALUES (1,'JSB Retail - Independence Ave','Windhoek');
INSERT INTO devices (device_id, fingerprint, device_type) VALUES (1,'POS-TERM-0007','pos_terminal');
INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, status, payout_amount, placed_at_utc, settled_at_utc) VALUES
  (4,'REQ-BET-0004',2,'retail','retail',100.00,0.00,'lost',0.00,'2026-09-11 13:00:00','2026-09-11 16:00:00');
INSERT INTO retail_bet_details (bet_id, location_id, device_id, ticket_number) VALUES (4,1,1,'TCK-000456');
INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc)
VALUES
  (10,2,2,'bet_stake','real',100.00,'debit',500.00,400.00,4,'bet_stake:4','2026-09-11 13:00:00');

-- A correction, recorded the only way the ledger allows: append, never edit.
-- An agent keyed a 50.00 goodwill credit instead of 15.00 (row 11). Row 12 reverses it in full,
-- pointing at it; row 13 posts the right amount. Player 2's balance is 450.00 between 09:00 and
-- 09:30, which is what query (c) returns for that moment, and 415.00 afterwards.
INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, reversal_of_wallet_txn_id, reason, created_by, idempotency_key, created_at_utc)
VALUES
  (11,2,2,'manual_adjustment','real',50.00,'credit',400.00,450.00,NULL,'Goodwill credit: delayed withdrawal (ticket OPS-2291)','ops:agent_007','manual:OPS-2291','2026-09-12 09:00:00'),
  (12,2,2,'reversal','real',50.00,'debit',450.00,400.00,11,'Keyed 50.00 instead of 15.00 (ticket OPS-2291)','ops:supervisor_002','reversal:11','2026-09-12 09:30:00'),
  (13,2,2,'manual_adjustment','real',15.00,'credit',400.00,415.00,NULL,'Goodwill credit: delayed withdrawal, corrected (ticket OPS-2291)','ops:supervisor_002','manual:OPS-2291:v2','2026-09-12 09:31:00');

-- Player 2's bonus: granted, then forfeited unwagered (the whole bonus balance is removed).
INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_player_bonus_id, idempotency_key, created_at_utc)
VALUES
  (14,2,2,'bonus_credit','bonus',25.00,'credit',0,25.00,2,'bonus_grant:2','2026-09-15 09:05:00'),
  (15,2,2,'bonus_debit','bonus',25.00,'debit',25.00,0,2,'bonus_forfeit:2','2026-09-20 10:00:00');

-- Casino: player 1 loses a 300.00 round.
INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, status, payout_amount, placed_at_utc, settled_at_utc) VALUES
  (5,'REQ-BET-0005',1,'casino','app',300.00,0.00,'lost',0.00,'2026-09-08 21:00:00','2026-09-08 21:00:04');
INSERT INTO casino_round_details (bet_id, game_id, provider_round_ref) VALUES (5,1,'PP-ROUND-000124');

-- Sportsbook accumulator: two legs, paid 10.00 from real money and 20.00 from player 3's bonus.
-- One leg loses, so the bet loses. The 30.00 stake counts towards the bonus rollover (odds >= 1.5).
INSERT INTO sports_events (event_id, sport, league, home_team, away_team, starts_at_utc) VALUES
  (2,'Football','Namibia Premier League','Tigers','Black Africa','2026-09-13 15:00:00'),
  (3,'Football','Namibia Premier League','Orlando Pirates','Civics','2026-09-13 17:00:00');
INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, player_bonus_id, status, payout_amount, placed_at_utc, settled_at_utc) VALUES
  (6,'REQ-BET-0006',3,'sportsbook','app',10.00,20.00,1,'lost',0.00,'2026-09-13 12:00:00','2026-09-13 19:00:00');
INSERT INTO sports_bet_details (bet_id, bet_class, total_odds, leg_count, min_odds_rule_applied) VALUES
  (6,'accumulator',3.990,2,1.500);
INSERT INTO bet_legs (bet_id, event_id, market, selection, odds, leg_result) VALUES
  (6,2,'match_winner','Tigers',1.900,'won'),
  (6,3,'match_winner','Civics',2.100,'lost');
INSERT INTO bonus_rollover_events (player_bonus_id, bet_id, contribution_amount, created_at_utc) VALUES
  (1,6,30.00,'2026-09-13 19:00:00');

INSERT INTO wallet_transactions
  (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction,
   balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc)
VALUES
  (16,1,1,'bet_stake','real',300.00,'debit',1190.00,890.00,5,'bet_stake:5','2026-09-08 21:00:00'),
  (17,3,3,'bet_stake','real',10.00,'debit',100.00,90.00,6,'bet_stake:6:real','2026-09-13 12:00:00'),
  (18,3,3,'bet_stake','bonus',20.00,'debit',30.00,10.00,6,'bet_stake:6:bonus','2026-09-13 12:00:00');


-- Row counts, to compare with the submission
SELECT 'internal_deposits' AS table_name, COUNT(*) AS n FROM jsb_assessment.internal_deposits
UNION ALL SELECT 'gateway_settlement', COUNT(*) FROM jsb_assessment.gateway_settlement
UNION ALL SELECT 'transactions', COUNT(*) FROM jsb_assessment.transactions
UNION ALL SELECT 'ingest_runs', COUNT(*) FROM jsb_assessment.ingest_runs
UNION ALL SELECT 'ingest_rejects', COUNT(*) FROM jsb_assessment.ingest_rejects
UNION ALL SELECT 'jsb_platform tables', COUNT(*) FROM information_schema.tables WHERE table_schema = 'jsb_platform';
