"""Write 01_load_submission_tables.sql: one script that loads this submission's 29 tables
into a local MySQL 8 / MariaDB 10.x (e.g. XAMPP), with the same rows every figure
in the submission was computed from.

  Exercise 1  jsb_assessment: internal_deposits, gateway_settlement (the supplied CSVs)
  Exercise 2  jsb_assessment: transactions, ingest_checkpoint, ingest_runs, ingest_rejects
              (the end state after the three documented runs)
  Exercise 3  jsb_platform:   23 tables (ddl.sql + seed.sql)

It only creates/replaces those 29 tables. Other tables already in jsb_assessment
are left alone (none share a name with these).
Usage: python build_load_sql.py
"""
import csv
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "exercise2-ingestion"))
from mock_api import build  # noqa: E402  deterministic source records (seeded)


def q(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'"


def inserts(table, cols, rows, batch=200):
    out = []
    for i in range(0, len(rows), batch):
        values = ",\n".join("(" + ", ".join(q(r[c]) for c in cols) + ")" for r in rows[i:i + batch])
        out.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n{values};")
    return out


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main():
    ex1 = ROOT / "exercise1-reconciliation"
    ex2 = ROOT / "exercise2-ingestion"
    ex3 = ROOT / "exercise3-schema-design"
    L = [
        "-- JSB assessment: load this submission's 29 tables into MySQL 8 / MariaDB 10.x.",
        "-- Generated by local_load/build_load_sql.py.",
        "-- WARNING: re-running DROPS and reloads these 29 tables. Any rows added or changed in them",
        "-- since the last load are lost. Tables not created by this script are never touched.",
        "-- MySQL Workbench: File > Open SQL Script, then Execute (lightning bolt).",
        "-- Command line (XAMPP): C:\\xampp\\mysql\\bin\\mysql.exe -u root < 01_load_submission_tables.sql",
        "SET NAMES utf8mb4;",
        "",
        "-- ===================== Exercise 1 =====================",
        (ex1 / "sql" / "01_schema.sql").read_text(encoding="utf-8"),
    ]
    dep = read_csv(ex1 / "internal_deposits.csv")
    gw = read_csv(ex1 / "gateway_settlement.csv")
    L += inserts("internal_deposits", ["deposit_id", "player_id", "created_at", "amount", "currency",
                                       "method", "gateway_ref", "status"], dep)
    L += inserts("gateway_settlement", ["gateway_txn_id", "merchant_ref", "settled_at", "gross_amount",
                                        "fee", "net_amount", "currency", "status"], gw)

    L += ["", "-- ===================== Exercise 2 =====================",
          (ex2 / "schema.sql").read_text(encoding="utf-8")]
    txn = read_csv(ROOT / "powerbi" / "data" / "transactions.csv")
    L += inserts("transactions", ["id", "player_id", "type", "amount", "currency", "status", "updated_at",
                                  "source_system", "ingested_at"], txn)
    runs = read_csv(ROOT / "powerbi" / "data" / "ingest_runs.csv")
    L += inserts("ingest_runs", ["run_id", "source_system", "started_at", "finished_at", "status",
                                 "pages_fetched", "rows_upserted", "rows_rejected", "rate_limit_hits",
                                 "server_error_hits"], runs)
    bad = build()["TX000777"]                    # the record run 2 quarantined
    L += inserts("ingest_rejects", ["run_id", "record_id", "reason", "raw_payload"],
                 [{"run_id": 2, "record_id": "TX000777", "reason": "missing player_id",
                   "raw_payload": json.dumps(bad)}])
    last = max(txn, key=lambda r: (r["updated_at"], r["id"]))
    L += inserts("ingest_checkpoint", ["source_system", "next_cursor", "last_updated_at", "last_id"],
                 [{"source_system": "mock_provider", "next_cursor": None,
                   "last_updated_at": last["updated_at"].replace(" ", "T") + "Z", "last_id": last["id"]}])

    L += ["", "-- ===================== Exercise 3 =====================",
          (ex3 / "ddl.sql").read_text(encoding="utf-8"),
          "USE jsb_platform;",
          (ex3 / "seed.sql").read_text(encoding="utf-8"),
          "",
          "-- Row counts, to compare with the submission",
          "SELECT 'internal_deposits' AS table_name, COUNT(*) AS n FROM jsb_assessment.internal_deposits",
          "UNION ALL SELECT 'gateway_settlement', COUNT(*) FROM jsb_assessment.gateway_settlement",
          "UNION ALL SELECT 'transactions', COUNT(*) FROM jsb_assessment.transactions",
          "UNION ALL SELECT 'ingest_runs', COUNT(*) FROM jsb_assessment.ingest_runs",
          "UNION ALL SELECT 'ingest_rejects', COUNT(*) FROM jsb_assessment.ingest_rejects",
          "UNION ALL SELECT 'jsb_platform tables', COUNT(*) FROM information_schema.tables "
          "WHERE table_schema = 'jsb_platform';"]
    out = HERE / "01_load_submission_tables.sql"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out.name}: {len(dep)} deposits, {len(gw)} settlements, {len(txn)} transactions, "
          f"{len(runs)} runs, 1 reject, checkpoint at {last['id']}")


if __name__ == "__main__":
    main()
