"""Write 01_load_submission_tables.sql: one script that loads this submission's 30 tables
into a local MariaDB 10.4+ (e.g. XAMPP; MySQL-compatible), with the same rows every figure
in the submission was computed from.

  Exercise 1  jsb_assessment: internal_deposits, gateway_settlement (the supplied CSVs)
  Exercise 2  jsb_assessment: transactions, ingest_checkpoint, ingest_runs, ingest_rejects
              (the end state after the three documented runs)
  Exercise 3  jsb_platform:   24 tables (ddl.sql + seed.sql)

It only creates/replaces those 30 tables. Other tables already in jsb_assessment
are left alone (none share a name with these).
Usage: python build_load_sql.py
"""
import csv
import json
import os
import sys
from pathlib import Path

import pymysql

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "exercise2-ingestion"))
from mock_api import build  # noqa: E402  deterministic source records (seeded)


def q(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'"


def inserts(table, cols, rows, batch=50):
    out = []
    for i in range(0, len(rows), batch):
        values = ",\n".join("(" + ", ".join(q(r[c]) for c in cols) + ")" for r in rows[i:i + batch])
        out.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n{values};")
    return out


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def main():
    ex1 = ROOT / "exercise1-reconciliation"
    ex2 = ROOT / "exercise2-ingestion"
    ex3 = ROOT / "exercise3-schema-design"
    L = [
        "-- JSB assessment: load this submission's 30 tables into MariaDB 10.4+ (e.g. XAMPP; MySQL-compatible).",
        "-- Generated by local_load/build_load_sql.py.",
        "-- WARNING: re-running DROPS and reloads these 30 tables. Any rows added or changed in them",
        "-- since the last load are lost. Tables not created by this script are never touched.",
        "-- MySQL Workbench: File > Open SQL Script, then Execute (lightning bolt).",
        "-- Command line (XAMPP): C:\\xampp\\mysql\\bin\\mysql.exe -u root < 01_load_submission_tables.sql",
        "SET NAMES utf8mb4;",
        "",
        "-- ===================== Exercise 1 =====================",
        (ex1 / "sql" / "01_schema.sql").read_text(encoding="utf-8"),
    ]
    dep = read_csv(ex1 / "internal_deposits.csv")
    gw = read_csv(ex1 / "gateway_settlement.csv")
    L += inserts("internal_deposits", ["deposit_id", "player_id", "created_at", "amount", "currency",
                                       "method", "gateway_ref", "status"], dep)
    L += inserts("gateway_settlement", ["gateway_txn_id", "merchant_ref", "settled_at", "gross_amount",
                                        "fee", "net_amount", "currency", "status"], gw)

    L += ["", "-- ===================== Exercise 2 =====================",
          (ex2 / "schema.sql").read_text(encoding="utf-8")]
    # Exercise 2: the tables exactly as the ingestion demo left them (exercise2-ingestion/demo.py
    # --database jsb_assessment), read from the database so every column and row is reproduced.
    conn = pymysql.connect(
        host=os.environ.get("DB_HOST", "127.0.0.1"), port=int(os.environ.get("DB_PORT", 3306)),
        unix_socket=os.environ.get("DB_SOCKET") or None, user=os.environ.get("DB_USER", "assess"),
        password=os.environ.get("DB_PASSWORD", "AssessPass123!"), database="jsb_assessment")
    ex2_counts = {}
    for table, order in [("transactions", "id"), ("ingest_runs", "run_id"),
                         ("ingest_rejects", "reject_id"), ("ingest_checkpoint", "source_system")]:
        cur = conn.cursor(pymysql.cursors.DictCursor)
        cur.execute(f"SELECT * FROM {table} ORDER BY {order}")
        rows = cur.fetchall()
        cols = [c for c in (rows[0].keys() if rows else []) if c != "payload_sha256"]   # generated column
        L += inserts(table, cols, rows)
        ex2_counts[table] = len(rows)
    conn.close()
    txn, runs = ex2_counts["transactions"], ex2_counts["ingest_runs"]

    L += ["", "-- ===================== Exercise 3 =====================",
          (ex3 / "ddl.sql").read_text(encoding="utf-8"),
          "USE jsb_platform;",
          (ex3 / "seed.sql").read_text(encoding="utf-8"),
          "",
          "-- Row counts, to compare with the submission",
          "SELECT 'internal_deposits' AS table_name, COUNT(*) AS n FROM jsb_assessment.internal_deposits",
          "UNION ALL SELECT 'gateway_settlement', COUNT(*) FROM jsb_assessment.gateway_settlement",
          "UNION ALL SELECT 'transactions', COUNT(*) FROM jsb_assessment.transactions",
          "UNION ALL SELECT 'ingest_runs', COUNT(*) FROM jsb_assessment.ingest_runs",
          "UNION ALL SELECT 'ingest_rejects', COUNT(*) FROM jsb_assessment.ingest_rejects",
          "UNION ALL SELECT 'jsb_platform tables', COUNT(*) FROM information_schema.tables "
          "WHERE table_schema = 'jsb_platform';"]
    text = "\n".join(L) + "\n"
    out = HERE / "01_load_submission_tables.sql"
    out.write_text(text, encoding="utf-8")
    # The same script in three parts (one per exercise), for clients that struggle with one
    # large script. Run them in order; each starts with the same header.
    header, rest = text.split("-- ===================== Exercise 1", 1)
    ex1, rest = rest.split("-- ===================== Exercise 2", 1)
    ex2, ex3 = rest.split("-- ===================== Exercise 3", 1)
    for name, body in [("01a_exercise1.sql", "-- ===================== Exercise 1" + ex1),
                       ("01b_exercise2.sql", "-- ===================== Exercise 2" + ex2),
                       ("01c_exercise3.sql", "-- ===================== Exercise 3" + ex3)]:
        (HERE / name).write_text(header + body, encoding="utf-8")
    print(f"wrote {out.name}: {len(dep)} deposits, {len(gw)} settlements, {txn} transactions, "
          f"{runs} runs, {ex2_counts['ingest_rejects']} reject(s), from the database")


if __name__ == "__main__":
    main()
