# Databricks notebook source
# MAGIC %md
# MAGIC # Exercise 3: players, wallets, bets and bonuses (Delta Lake)
# MAGIC The 23-table design from `exercise3-schema-design/ddl.sql`, translated to Delta, with the same seed data
# MAGIC and the four required queries.
# MAGIC
# MAGIC **How MySQL features map to Databricks**
# MAGIC
# MAGIC | MySQL | Databricks (Delta, Unity Catalog) |
# MAGIC |---|---|
# MAGIC | `AUTO_INCREMENT` | `GENERATED BY DEFAULT AS IDENTITY`: explicit ids still allowed, as the seed uses them |
# MAGIC | `ENUM(...)` | `STRING` plus a `CHECK` constraint. Delta **enforces** it, and the demo below proves it |
# MAGIC | `CHECK`, `NOT NULL` | Enforced by Delta |
# MAGIC | `PRIMARY KEY`, `FOREIGN KEY` | Declared in Unity Catalog, but **informational only**: not enforced |
# MAGIC | `UNIQUE` | Not available. Uniqueness comes from the load (`MERGE` on the key) and is **checked** below |
# MAGIC | `DEFAULT` | Column defaults (the `allowColumnDefaults` table feature) |
# MAGIC | Secondary indexes | None in Delta. The two large tables use liquid clustering (`CLUSTER BY`) on their access path |
# MAGIC | `GENERATED ... STORED` | Delta generated column |
# MAGIC
# MAGIC Because keys aren't enforced, this notebook *proves* they hold: every primary and natural key is
# MAGIC checked for duplicates, and every foreign key for orphans.

# COMMAND ----------

# MAGIC %run ./00_config

# COMMAND ----------

# MAGIC %md ## 1. Create the 23 tables

# COMMAND ----------

DDL = __DDL_STATEMENTS__

for stmt in DDL:
    spark.sql(stmt)
print(f"{len(DDL)} tables created")

# COMMAND ----------

# MAGIC %md ## 2. Enforced constraints (CHECK), and informational keys (PK/FK, Unity Catalog only)

# COMMAND ----------

CHECKS = __CHECK_CONSTRAINTS__     # (table, constraint name, expression): ENUM values and the MySQL CHECKs
for table, name, expr in CHECKS:
    spark.sql(f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({expr})")
print(f"{len(CHECKS)} CHECK constraints added (enforced on every write)")

KEY_CONSTRAINTS = __KEY_CONSTRAINTS__   # ALTER TABLE ... PRIMARY KEY / FOREIGN KEY (parents first)
if ON_DATABRICKS:
    for stmt in KEY_CONSTRAINTS:
        spark.sql(stmt)
    print(f"{len(KEY_CONSTRAINTS)} primary and foreign keys declared in Unity Catalog (informational)")
else:
    print(f"local run: {len(KEY_CONSTRAINTS)} PK/FK declarations skipped (Unity Catalog only)")

# COMMAND ----------

# MAGIC %md ## 3. Seed data (the same rows as `seed.sql`)

# COMMAND ----------

SEED = __SEED_STATEMENTS__
for stmt in SEED:
    spark.sql(stmt)
display(spark.sql("""SELECT 'players' AS t, COUNT(*) AS n FROM players UNION ALL SELECT 'bets', COUNT(*) FROM bets
                     UNION ALL SELECT 'wallet_transactions', COUNT(*) FROM wallet_transactions
                     UNION ALL SELECT 'player_bonuses', COUNT(*) FROM player_bonuses"""))

# COMMAND ----------

# MAGIC %md ## 4. Delta enforces CHECK constraints: a negative stake is refused

# COMMAND ----------

try:
    spark.sql("""INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount,
                 stake_bonus_amount, status, payout_amount, placed_at_utc)
                 VALUES (99, 'REQ-BAD', 1, 'casino', 'app', -5, 0, 'open', 0, current_timestamp())""")
    refused = False
except Exception as e:  # noqa: BLE001
    refused = "CHECK" in str(e).upper() or "constraint" in str(e).lower()
    print("refused:", str(e).splitlines()[0][:160])
check(refused, "a negative stake violates ck_bets_stake_nonneg and is rejected")

# COMMAND ----------

# MAGIC %md ## 5. Duplicate-free: every primary key and natural key; referential integrity: every foreign key

# COMMAND ----------

KEYS = __KEY_CHECKS__            # (table, [columns], 'primary key' | 'unique')
FKS = __FK_CHECKS__              # (child table, [columns], parent table, [columns])

key_rows = []
for table, cols, kind in KEYS:
    c = ", ".join(cols)
    dupes = spark.sql(f"SELECT COUNT(*) FROM (SELECT {c} FROM {table} GROUP BY {c} HAVING COUNT(*) > 1)").first()[0]
    key_rows.append((table, kind, c, dupes))
fk_rows = []
for child, ccols, parent, pcols in FKS:
    on = " AND ".join(f"c.{a} = p.{b}" for a, b in zip(ccols, pcols))
    notnull = " AND ".join(f"c.{a} IS NOT NULL" for a in ccols)
    orphans = spark.sql(f"SELECT COUNT(*) FROM {child} c LEFT ANTI JOIN {parent} p ON {on} WHERE {notnull}").first()[0]
    fk_rows.append((f"{child}({', '.join(ccols)})", f"{parent}({', '.join(pcols)})", orphans))

display(spark.createDataFrame(key_rows, "table STRING, key STRING, columns STRING, duplicate_keys BIGINT"))
display(spark.createDataFrame(fk_rows, "foreign_key STRING, references STRING, orphan_rows BIGINT"))
check(all(r[3] == 0 for r in key_rows), f"no duplicates on any of the {len(key_rows)} primary and natural keys")
check(all(r[2] == 0 for r in fk_rows), f"no orphans on any of the {len(fk_rows)} foreign keys")

# COMMAND ----------

# MAGIC %md ## 6. The four required queries
# MAGIC Assumption, as in the MySQL version: GGR = stakes − payouts on settled bets, and NGR = GGR − realised bonus cost.

# COMMAND ----------

# MAGIC %md ### (a) NGR by product for a month

# COMMAND ----------

q_a = spark.sql("""
WITH product_ggr AS (
    SELECT product, SUM(stake_real_amount + stake_bonus_amount) AS turnover, SUM(payout_amount) AS payouts,
           SUM(stake_real_amount + stake_bonus_amount) - SUM(payout_amount) AS ggr
    FROM bets
    WHERE settled_at_utc >= '2026-09-01' AND settled_at_utc < '2026-10-01' AND status IN ('won', 'lost')
    GROUP BY product
),
product_bonus_cost AS (
    SELECT b.product, SUM(wt.amount) AS bonus_cost
    FROM wallet_transactions wt JOIN bets b ON b.bet_id = wt.related_bet_id
    WHERE wt.txn_type = 'bet_stake' AND wt.balance_type = 'bonus' AND b.status = 'lost'
      AND b.settled_at_utc >= '2026-09-01' AND b.settled_at_utc < '2026-10-01'
    GROUP BY b.product
)
SELECT g.product, g.turnover, g.payouts, g.ggr, COALESCE(c.bonus_cost, 0) AS bonus_cost,
       g.ggr - COALESCE(c.bonus_cost, 0) AS ngr
FROM product_ggr g LEFT JOIN product_bonus_cost c ON c.product = g.product
ORDER BY g.product""")
display(q_a)
ngr = {r["product"]: float(r["ngr"]) for r in q_a.collect()}
check(ngr == {"casino": -30.0, "retail": 100.0, "sportsbook": -160.0}, "NGR: casino -30, retail 100, sportsbook -160")

# COMMAND ----------

# MAGIC %md ### (b) Bonus cost as a % of NGR, by campaign

# COMMAND ----------

q_b = spark.sql("""
WITH campaign_cost AS (
    SELECT pb.campaign_id, SUM(pb.granted_amount) AS bonus_cost
    FROM player_bonuses pb
    WHERE pb.status IN ('completed', 'expired', 'forfeited')
      AND pb.resolved_at_utc >= '2026-09-01' AND pb.resolved_at_utc < '2026-10-01'
    GROUP BY pb.campaign_id
),
period_ggr AS (
    SELECT SUM(stake_real_amount + stake_bonus_amount) - SUM(payout_amount) AS total_ggr
    FROM bets WHERE settled_at_utc >= '2026-09-01' AND settled_at_utc < '2026-10-01' AND status IN ('won', 'lost')
),
period_bonus_cost AS (
    SELECT SUM(wt.amount) AS total_bonus_cost
    FROM wallet_transactions wt JOIN bets b ON b.bet_id = wt.related_bet_id
    WHERE wt.txn_type = 'bet_stake' AND wt.balance_type = 'bonus' AND b.status = 'lost'
      AND b.settled_at_utc >= '2026-09-01' AND b.settled_at_utc < '2026-10-01'
),
period_ngr AS (
    SELECT (SELECT total_ggr FROM period_ggr) - COALESCE((SELECT total_bonus_cost FROM period_bonus_cost), 0) AS total_ngr
)
SELECT bc.name AS campaign, cc.bonus_cost,
       ROUND(100 * cc.bonus_cost / NULLIF((SELECT total_ngr FROM period_ngr), 0), 2) AS bonus_cost_pct_of_ngr
FROM campaign_cost cc JOIN bonus_campaigns bc ON bc.campaign_id = cc.campaign_id""")
display(q_b)
r = q_b.first()
check(r["campaign"] == "Registration Bonus" and float(r["bonus_cost_pct_of_ngr"]) == -27.78,
      "Registration Bonus cost is -27.78% of NGR")

# COMMAND ----------

# MAGIC %md ### (c) A player's balance at a given date and time (from the ledger)

# COMMAND ----------

PLAYER_ID, AS_OF = 1, "2026-09-06 00:00:00"
q_c = spark.sql(f"""
SELECT balance_type, SUM(CASE WHEN direction = 'credit' THEN amount ELSE -amount END) AS balance_as_of
FROM wallet_transactions
WHERE player_id = {PLAYER_ID} AND created_at_utc <= '{AS_OF}' AND status = 'posted'
GROUP BY balance_type""")
display(q_c)
check([(r[0], float(r[1])) for r in q_c.collect()] == [("real", 1160.0)], "player 1 real balance on 2026-09-06 is 1,160.00")

# COMMAND ----------

# MAGIC %md ### (d) Deposits that failed, then the player succeeded later

# COMMAND ----------

q_d = spark.sql("""
SELECT f.player_id, f.deposit_attempt_id AS failed_attempt_id, f.created_at_utc AS failed_at,
       s.deposit_attempt_id AS succeeded_attempt_id, s.created_at_utc AS succeeded_at,
       timestampdiff(MINUTE, f.created_at_utc, s.created_at_utc) AS minutes_to_success, s.amount AS succeeded_amount
FROM deposit_attempts f
JOIN deposit_attempts s
  ON s.player_id = f.player_id AND s.status = 'success'
 AND s.created_at_utc > f.created_at_utc AND s.created_at_utc <= f.created_at_utc + INTERVAL 24 HOURS
WHERE f.status = 'failed'
  AND NOT EXISTS (SELECT 1 FROM deposit_attempts s2
                  WHERE s2.player_id = f.player_id AND s2.status = 'success'
                    AND s2.created_at_utc > f.created_at_utc AND s2.created_at_utc < s.created_at_utc)
ORDER BY f.created_at_utc""")
display(q_d)
rows = q_d.collect()
check(len(rows) == 1 and rows[0]["player_id"] == 2 and rows[0]["minutes_to_success"] == 4,
      "player 2 failed, then succeeded 4 minutes later")

# COMMAND ----------

# MAGIC %md ## 7. The wallet balance cache equals the ledger

# COMMAND ----------

drift = spark.sql("""
SELECT w.wallet_id, w.real_balance, w.bonus_balance, l.real_ledger, l.bonus_ledger
FROM wallets w
LEFT JOIN (SELECT wallet_id,
                  SUM(CASE WHEN balance_type = 'real' THEN CASE WHEN direction = 'credit' THEN amount ELSE -amount END ELSE 0 END) AS real_ledger,
                  SUM(CASE WHEN balance_type = 'bonus' THEN CASE WHEN direction = 'credit' THEN amount ELSE -amount END ELSE 0 END) AS bonus_ledger
           FROM wallet_transactions WHERE status = 'posted' GROUP BY wallet_id) l ON l.wallet_id = w.wallet_id
WHERE w.real_balance <> COALESCE(l.real_ledger, 0) OR w.bonus_balance <> COALESCE(l.bonus_ledger, 0)""")
check(drift.count() == 0, "every wallet's cached balance equals the sum of its ledger")
