"""Build the Databricks notebooks from the project's own files, so Databricks runs on the same data.

  src/*.py (templates)  +  exercise1 CSVs, exercise2 mock_api.py / ingest.py, exercise3 ddl.sql / seed.sql
      -> notebooks/*.py (Databricks source format)  and  JSB_Databricks_Notebooks.zip

Exercise 3's MySQL DDL is translated to Delta here (rules in 03_exercise3_schema.py's header) and
written into the notebook as plain SQL, so the notebook does not depend on this script to run.
Usage: python build_notebooks.py
"""
import csv
import inspect
import re
import sys
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
EX1, EX2, EX3 = ROOT / "exercise1-reconciliation", ROOT / "exercise2-ingestion", ROOT / "exercise3-schema-design"


# --------------------------------------------------------------------------- Exercise 3 DDL
def split_top_level(body):
    """Split a CREATE TABLE body on commas that are not inside parentheses."""
    parts, depth, cur = [], 0, ""
    for ch in body:
        depth += ch == "("
        depth -= ch == ")"
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += ch
    parts.append(cur)
    return [p.strip() for p in parts if p.strip()]


def translate_ddl(sql):
    sql = re.sub(r"--[^\n]*", "", sql)
    tables, checks, pks, fks, keys = [], [], [], [], []
    for name, body in re.findall(r"CREATE TABLE (\w+) \((.*?)\n\) ENGINE=InnoDB;", sql, flags=re.S):
        cols, pk = [], None
        for part in split_top_level(body):
            p = " ".join(part.split())
            if p.startswith("PRIMARY KEY"):
                pk = re.findall(r"\((.*)\)", p)[0].replace(" ", "").split(",")
            elif p.startswith("CONSTRAINT") and "FOREIGN KEY" in p:
                cname, ccols, parent, pcols = re.match(
                    r"CONSTRAINT (\w+) FOREIGN KEY \((.*?)\) REFERENCES (\w+)\((.*?)\)", p).groups()
                fks.append((name, cname, ccols.replace(" ", "").split(","), parent, pcols.replace(" ", "").split(",")))
            elif p.startswith("CONSTRAINT") and "CHECK" in p:
                cname, expr = re.match(r"CONSTRAINT (\w+) CHECK \((.*)\)$", p).groups()
                checks.append((name, cname, expr))
            elif p.startswith("UNIQUE KEY"):
                keys.append((name, re.findall(r"\((.*)\)", p)[0].replace(" ", "").split(","), "unique"))
            elif p.startswith("KEY "):
                continue                                    # secondary index: no equivalent in Delta
            else:
                cols.append(translate_column(name, p, checks, keys))
                if " PRIMARY KEY" in p:
                    pk = [p.split()[0]]
        tables.append((name, cols, pk))
        keys.insert(len(keys), (name, pk, "primary key"))
    # forward-reference FKs added at the end of ddl.sql
    for table, body in re.findall(r"ALTER TABLE (\w+)\s+(ADD CONSTRAINT.*?);", sql, flags=re.S):
        for cname, ccols, parent, pcols in re.findall(
                r"ADD CONSTRAINT (\w+) FOREIGN KEY \((.*?)\) REFERENCES (\w+)\((.*?)\)", body):
            fks.append((table, cname, [ccols], parent, [pcols]))
    return tables, checks, pks_from(tables), fks, keys


def pks_from(tables):
    return {name: pk for name, _, pk in tables}


def translate_column(table, p, checks, keys):
    name, rest = p.split(" ", 1)
    t = rest
    enum = re.match(r"ENUM\((.*?)\)", t)
    if enum:
        checks.append((table, f"ck_{table}_{name}", f"{name} IN ({enum.group(1)})"))
        dtype, t = "STRING", t[enum.end():]
    else:
        m = re.match(r"(\w+(?:\([\d, ]+\))?(?: UNSIGNED)?)", t)
        mysql_type, t = m.group(1), t[m.end():]
        base = mysql_type.split("(")[0].replace(" UNSIGNED", "").upper()
        if base in ("VARCHAR", "CHAR", "JSON", "VARBINARY"):
            dtype = "STRING"
        elif base == "DATETIME":
            dtype = "TIMESTAMP"
        elif base in ("BIGINT", "INT"):
            dtype = "BIGINT" if (base == "BIGINT" or name.endswith("_id")) else "INT"
        elif base == "SMALLINT":
            dtype = "INT"
        else:
            dtype = mysql_type                              # DECIMAL(p,s), DATE
    gen = re.search(r"GENERATED ALWAYS AS \((.*)\) STORED", t)
    out = f"{name} {dtype}"
    if gen:
        # Delta needs the expression's type to equal the column's (DECIMAL(18,4) + DECIMAL(18,4) is DECIMAL(19,4))
        return out + f" GENERATED ALWAYS AS (CAST({gen.group(1)} AS {dtype}))"
    if "AUTO_INCREMENT" in t:
        return f"{name} BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY"
    if re.search(r"(?<!NOT )\bNULL\b", t) is None and ("NOT NULL" in t or "PRIMARY KEY" in t):
        out += " NOT NULL"
    d = re.search(r"DEFAULT (CURRENT_TIMESTAMP\(6\)|'[^']*'|[\d.]+)", t)
    if d:
        val = d.group(1)
        out += " DEFAULT " + ("current_timestamp()" if val.startswith("CURRENT_TIMESTAMP")
                              else (f"CAST({val} AS {dtype})" if dtype.startswith("DECIMAL") else val))
    if re.search(r"\bUNIQUE\b", t):
        keys.append((table, [name], "unique"))
    return out


CLUSTER = {"wallet_transactions": "player_id, created_at_utc", "bets": "player_id, placed_at_utc"}


def ddl_statements(tables):
    out = []
    for name, cols, _ in tables:
        cluster = f"\nCLUSTER BY ({CLUSTER[name]})" if name in CLUSTER else ""
        out.append(f"CREATE OR REPLACE TABLE {name} (\n    " + ",\n    ".join(cols) + "\n) USING DELTA" + cluster
                   + "\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')")
    return out


def key_constraints(tables, fks):
    stmts = [f"ALTER TABLE {n} ADD CONSTRAINT pk_{n} PRIMARY KEY ({', '.join(pk)})" for n, _, pk in tables if pk]
    stmts += [f"ALTER TABLE {child} ADD CONSTRAINT {cname} FOREIGN KEY ({', '.join(cc)}) "
              f"REFERENCES {parent} ({', '.join(pc)})" for child, cname, cc, parent, pc in fks]
    return stmts


def value_tuples(values):
    """Split 'VALUES (..),(..)' into tuples, respecting quotes and parentheses."""
    out, depth, cur, quote = [], 0, "", False
    for ch in values:
        if ch == "'" :
            quote = not quote
        if not quote and ch == "(":
            depth += 1
            if depth == 1:
                cur = ""
                continue
        if not quote and ch == ")":
            depth -= 1
            if depth == 0:
                out.append(cur)
                continue
        if depth >= 1:
            cur += ch
    return out


def seed_statements(sql, identity_cols):
    """INSERTs from seed.sql. Where MySQL's AUTO_INCREMENT numbered rows the seed leaves out, the id is
    written explicitly (1, 2, ... per table: exactly what AUTO_INCREMENT assigns), so the data is identical."""
    sql = re.sub(r"--[^\n]*", "", sql)
    counters, out = {}, []
    for stmt in [" ".join(s.split()) for s in sql.split(";") if s.strip().upper().startswith("INSERT")]:
        m = re.match(r"INSERT INTO (\w+) \((.*?)\) VALUES (.*)$", stmt)
        table, cols, values = m.group(1), [c.strip() for c in m.group(2).split(",")], m.group(3)
        idc = identity_cols.get(table)
        if idc and idc not in cols:
            rows = []
            for t in value_tuples(values):
                counters[table] = counters.get(table, 0) + 1
                rows.append(f"({counters[table]},{t})")
            stmt = f"INSERT INTO {table} ({idc}, {', '.join(cols)}) VALUES {', '.join(rows)}"
        out.append(stmt)
    return out


# --------------------------------------------------------------------------- build
def pylist(items):
    return "[\n" + "".join(f"    {item!r},\n" for item in items) + "]"


def main():
    tables, checks, _, fks, keys = translate_ddl((EX3 / "ddl.sql").read_text(encoding="utf-8"))
    sys.path.insert(0, str(EX2))
    import ingest  # noqa: E402  (only to copy two functions' source unchanged)
    mock = (EX2 / "mock_api.py").read_text(encoding="utf-8").split('if __name__ == "__main__":')[0]
    helpers = inspect.getsource(ingest.api_get) + "\n\n" + inspect.getsource(ingest.validate)

    expected = {}
    with open(EX1 / "evidence" / "agreement_by_category.csv", newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            expected[r["category"]] = (int(r["n_sql"]), round(float(r["rand_sql"]), 2))

    fill = {
        "__INTERNAL_DEPOSITS_CSV__": (EX1 / "internal_deposits.csv").read_text(encoding="utf-8").strip(),
        "__GATEWAY_SETTLEMENT_CSV__": (EX1 / "gateway_settlement.csv").read_text(encoding="utf-8").strip(),
        "__EXPECTED_BY_CATEGORY__": "{\n" + "".join(f"    {k!r}: {v!r},\n" for k, v in sorted(expected.items())) + "}",
        "__MOCK_API_SOURCE__": mock.strip(),
        "__INGEST_HELPERS_SOURCE__": helpers.strip(),
        "__DDL_STATEMENTS__": pylist(ddl_statements(tables)),
        "__CHECK_CONSTRAINTS__": pylist(checks),
        "__KEY_CONSTRAINTS__": pylist(key_constraints(tables, fks)),
        "__SEED_STATEMENTS__": pylist(seed_statements((EX3 / "seed.sql").read_text(encoding="utf-8"),
                                                      {n: c.split()[0] for n, cols, _ in tables for c in cols
                                                       if "AS IDENTITY" in c})),
        "__KEY_CHECKS__": pylist(k for k in keys if k[1]),
        "__FK_CHECKS__": pylist((c, cc, p, pc) for c, _, cc, p, pc in fks),
    }
    out_dir = HERE / "notebooks"
    out_dir.mkdir(exist_ok=True)
    written = []
    for src in sorted((HERE / "src").glob("*.py")):
        text = src.read_text(encoding="utf-8")
        for key, value in fill.items():
            text = text.replace(key, value)
        leftover = re.findall(r"__[A-Z_]+__", text.replace("__name__", "").replace("__main__", "")
                              .replace("__file__", "").replace("__init__", ""))
        assert not leftover, f"{src.name}: unfilled {leftover}"
        (out_dir / src.name).write_text(text, encoding="utf-8")
        written.append(out_dir / src.name)
    with zipfile.ZipFile(HERE / "JSB_Databricks_Notebooks.zip", "w", zipfile.ZIP_DEFLATED) as z:
        for p in written:
            z.write(p, f"JSB_Assessment/{p.name}")
    print(f"notebooks: {', '.join(p.name for p in written)}")
    print(f"exercise 3: {len(tables)} tables, {len(checks)} CHECK constraints, {len(fks)} foreign keys, "
          f"{sum(1 for k in keys if k[1])} keys checked for duplicates")


if __name__ == "__main__":
    main()
