# Databricks notebook source
# MAGIC %md
# MAGIC # Exercise 3: players, wallets, bets and bonuses (Delta Lake)
# MAGIC The 23-table design from `exercise3-schema-design/ddl.sql`, translated to Delta, with the same seed data
# MAGIC and the four required queries.
# MAGIC
# MAGIC **How MySQL features map to Databricks**
# MAGIC
# MAGIC | MySQL | Databricks (Delta, Unity Catalog) |
# MAGIC |---|---|
# MAGIC | `AUTO_INCREMENT` | `GENERATED BY DEFAULT AS IDENTITY`: explicit ids still allowed, as the seed uses them |
# MAGIC | `ENUM(...)` | `STRING` plus a `CHECK` constraint. Delta **enforces** it, and the demo below proves it |
# MAGIC | `CHECK`, `NOT NULL` | Enforced by Delta |
# MAGIC | `PRIMARY KEY`, `FOREIGN KEY` | Declared in Unity Catalog, but **informational only**: not enforced |
# MAGIC | `UNIQUE` | Not available. Uniqueness comes from the load (`MERGE` on the key) and is **checked** below |
# MAGIC | `DEFAULT` | Column defaults (the `allowColumnDefaults` table feature) |
# MAGIC | Secondary indexes | None in Delta. The two large tables use liquid clustering (`CLUSTER BY`) on their access path |
# MAGIC | `GENERATED ... STORED` | Delta generated column |
# MAGIC
# MAGIC Because keys aren't enforced, this notebook *proves* they hold: every primary and natural key is
# MAGIC checked for duplicates, and every foreign key for orphans.

# COMMAND ----------

# MAGIC %run ./00_config

# COMMAND ----------

# MAGIC %md ## 1. Create the 23 tables

# COMMAND ----------

DDL = [
    "CREATE OR REPLACE TABLE affiliates (\n    affiliate_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    affiliate_code STRING NOT NULL,\n    name STRING NOT NULL,\n    traffic_source STRING NOT NULL,\n    created_at_utc TIMESTAMP NOT NULL DEFAULT current_timestamp()\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE players (\n    player_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    registered_at_utc TIMESTAMP NOT NULL,\n    kyc_status STRING NOT NULL DEFAULT 'not_started',\n    vip_tier STRING NOT NULL DEFAULT 'standard',\n    status STRING NOT NULL DEFAULT 'active',\n    status_reason STRING,\n    traffic_source STRING NOT NULL,\n    affiliate_id BIGINT,\n    preferred_currency STRING NOT NULL DEFAULT 'NAD',\n    created_at_utc TIMESTAMP NOT NULL DEFAULT current_timestamp(),\n    updated_at_utc TIMESTAMP NOT NULL DEFAULT current_timestamp()\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE player_identity (\n    player_id BIGINT NOT NULL,\n    first_name STRING NOT NULL,\n    last_name STRING NOT NULL,\n    date_of_birth DATE NOT NULL,\n    national_id_number STRING NOT NULL,\n    email STRING NOT NULL,\n    phone STRING NOT NULL,\n    address_line1 STRING,\n    address_city STRING,\n    address_country STRING NOT NULL,\n    updated_at_utc TIMESTAMP NOT NULL DEFAULT current_timestamp()\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE player_vip_tier_history (\n    player_id BIGINT NOT NULL,\n    vip_tier STRING NOT NULL,\n    valid_from_utc TIMESTAMP NOT NULL,\n    valid_to_utc TIMESTAMP,\n    changed_by STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE player_tag_history (\n    tag_history_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    player_id BIGINT NOT NULL,\n    tag STRING NOT NULL,\n    valid_from_utc TIMESTAMP NOT NULL,\n    valid_to_utc TIMESTAMP\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE wallets (\n    wallet_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    player_id BIGINT NOT NULL,\n    currency STRING NOT NULL DEFAULT 'NAD',\n    real_balance DECIMAL(18,4) NOT NULL DEFAULT CAST(0 AS DECIMAL(18,4)),\n    bonus_balance DECIMAL(18,4) NOT NULL DEFAULT CAST(0 AS DECIMAL(18,4)),\n    updated_at_utc TIMESTAMP NOT NULL DEFAULT current_timestamp()\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE wallet_transactions (\n    wallet_txn_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    wallet_id BIGINT NOT NULL,\n    player_id BIGINT NOT NULL,\n    txn_type STRING NOT NULL,\n    balance_type STRING NOT NULL,\n    amount DECIMAL(18,4) NOT NULL,\n    direction STRING NOT NULL,\n    balance_before DECIMAL(18,4) NOT NULL,\n    balance_after DECIMAL(18,4) NOT NULL,\n    related_deposit_attempt_id BIGINT,\n    related_withdrawal_id BIGINT,\n    related_bet_id BIGINT,\n    related_player_bonus_id BIGINT,\n    reversal_of_wallet_txn_id BIGINT,\n    idempotency_key STRING NOT NULL,\n    source_system STRING NOT NULL DEFAULT 'platform',\n    status STRING NOT NULL DEFAULT 'posted',\n    created_at_utc TIMESTAMP NOT NULL,\n    ingested_at_utc TIMESTAMP NOT NULL DEFAULT current_timestamp()\n) USING DELTA\nCLUSTER BY (player_id, created_at_utc)\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE payment_methods (\n    method_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    method_code STRING NOT NULL,\n    rail_family STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE deposit_attempts (\n    deposit_attempt_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    player_id BIGINT NOT NULL,\n    method_id BIGINT NOT NULL,\n    amount DECIMAL(18,4) NOT NULL,\n    currency STRING NOT NULL,\n    gateway_ref STRING NOT NULL,\n    status STRING NOT NULL,\n    created_at_utc TIMESTAMP NOT NULL,\n    settled_at_utc TIMESTAMP\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE withdrawal_requests (\n    withdrawal_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    request_id STRING NOT NULL,\n    player_id BIGINT NOT NULL,\n    method_id BIGINT NOT NULL,\n    amount DECIMAL(18,4) NOT NULL,\n    currency STRING NOT NULL,\n    status STRING NOT NULL,\n    requested_at_utc TIMESTAMP NOT NULL,\n    paid_at_utc TIMESTAMP\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE bets (\n    bet_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    request_id STRING NOT NULL,\n    player_id BIGINT NOT NULL,\n    product STRING NOT NULL,\n    channel STRING NOT NULL,\n    stake_real_amount DECIMAL(18,4) NOT NULL DEFAULT CAST(0 AS DECIMAL(18,4)),\n    stake_bonus_amount DECIMAL(18,4) NOT NULL DEFAULT CAST(0 AS DECIMAL(18,4)),\n    total_stake DECIMAL(18,4) GENERATED ALWAYS AS (stake_real_amount + stake_bonus_amount),\n    status STRING NOT NULL DEFAULT 'open',\n    payout_amount DECIMAL(18,4) NOT NULL DEFAULT CAST(0 AS DECIMAL(18,4)),\n    placed_at_utc TIMESTAMP NOT NULL,\n    settled_at_utc TIMESTAMP\n) USING DELTA\nCLUSTER BY (player_id, placed_at_utc)\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE sports_events (\n    event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    sport STRING NOT NULL,\n    league STRING NOT NULL,\n    home_team STRING NOT NULL,\n    away_team STRING NOT NULL,\n    starts_at_utc TIMESTAMP NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE sports_bet_details (\n    bet_id BIGINT NOT NULL,\n    bet_class STRING NOT NULL,\n    total_odds DECIMAL(10,3) NOT NULL,\n    leg_count INT NOT NULL,\n    min_odds_rule_applied DECIMAL(10,3)\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE bet_legs (\n    leg_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    bet_id BIGINT NOT NULL,\n    event_id BIGINT NOT NULL,\n    market STRING NOT NULL,\n    selection STRING NOT NULL,\n    odds DECIMAL(10,3) NOT NULL,\n    leg_result STRING NOT NULL DEFAULT 'pending'\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE game_providers (\n    provider_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    name STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE games (\n    game_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    provider_id BIGINT NOT NULL,\n    name STRING NOT NULL,\n    category STRING NOT NULL,\n    rtp_theoretical DECIMAL(6,3) NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE casino_round_details (\n    bet_id BIGINT NOT NULL,\n    game_id BIGINT NOT NULL,\n    provider_round_ref STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE retail_locations (\n    location_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    name STRING NOT NULL,\n    address_city STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE devices (\n    device_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    fingerprint STRING NOT NULL,\n    device_type STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE retail_bet_details (\n    bet_id BIGINT NOT NULL,\n    location_id BIGINT NOT NULL,\n    device_id BIGINT NOT NULL,\n    ticket_number STRING NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE bonus_campaigns (\n    campaign_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    name STRING NOT NULL,\n    campaign_type STRING NOT NULL,\n    trigger_rule STRING NOT NULL,\n    audience_rule STRING NOT NULL,\n    rollover_multiple DECIMAL(6,2) NOT NULL,\n    min_odds DECIMAL(10,3),\n    max_stake_while_active DECIMAL(18,4),\n    expiry_days INT NOT NULL,\n    valid_from_utc TIMESTAMP NOT NULL,\n    valid_to_utc TIMESTAMP,\n    terms_json STRING\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE player_bonuses (\n    player_bonus_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    player_id BIGINT NOT NULL,\n    campaign_id BIGINT NOT NULL,\n    granted_amount DECIMAL(18,4) NOT NULL,\n    rollover_required DECIMAL(18,4) NOT NULL,\n    rollover_progress DECIMAL(18,4) NOT NULL DEFAULT CAST(0 AS DECIMAL(18,4)),\n    status STRING NOT NULL DEFAULT 'active',\n    granted_at_utc TIMESTAMP NOT NULL,\n    expires_at_utc TIMESTAMP NOT NULL,\n    resolved_at_utc TIMESTAMP\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
    "CREATE OR REPLACE TABLE bonus_rollover_events (\n    rollover_event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n    player_bonus_id BIGINT NOT NULL,\n    bet_id BIGINT NOT NULL,\n    contribution_amount DECIMAL(18,4) NOT NULL,\n    created_at_utc TIMESTAMP NOT NULL\n) USING DELTA\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')",
]

for stmt in DDL:
    spark.sql(stmt)
print(f"{len(DDL)} tables created")

# COMMAND ----------

# MAGIC %md ## 2. Enforced constraints (CHECK), and informational keys (PK/FK, Unity Catalog only)

# COMMAND ----------

CHECKS = [
    ('players', 'ck_players_kyc_status', "kyc_status IN ('not_started','pending','verified','rejected')"),
    ('players', 'ck_players_status', "status IN ('active','blocked','self_excluded','closed')"),
    ('wallets', 'ck_wallet_nonneg', 'real_balance >= 0 AND bonus_balance >= 0'),
    ('wallet_transactions', 'ck_wallet_transactions_txn_type', "txn_type IN ('deposit','withdrawal','bet_stake','bet_win','bonus_credit', 'bonus_debit','refund','reversal','manual_adjustment')"),
    ('wallet_transactions', 'ck_wallet_transactions_balance_type', "balance_type IN ('real','bonus')"),
    ('wallet_transactions', 'ck_wallet_transactions_direction', "direction IN ('credit','debit')"),
    ('wallet_transactions', 'ck_wallet_transactions_status', "status IN ('posted','reversed')"),
    ('deposit_attempts', 'ck_deposit_attempts_status', "status IN ('initiated','success','failed')"),
    ('withdrawal_requests', 'ck_withdrawal_requests_status', "status IN ('requested','approved','paid','failed','cancelled')"),
    ('bets', 'ck_bets_product', "product IN ('sportsbook','casino','retail')"),
    ('bets', 'ck_bets_channel', "channel IN ('web','app','retail')"),
    ('bets', 'ck_bets_status', "status IN ('open','won','lost','void','cashed_out')"),
    ('bets', 'ck_bets_stake_nonneg', 'stake_real_amount >= 0 AND stake_bonus_amount >= 0'),
    ('sports_bet_details', 'ck_sports_bet_details_bet_class', "bet_class IN ('single','accumulator')"),
    ('bet_legs', 'ck_bet_legs_leg_result', "leg_result IN ('pending','won','lost','void')"),
    ('bonus_campaigns', 'ck_bonus_campaigns_campaign_type', "campaign_type IN ('registration','deposit_match','cashback','free_spins','other')"),
    ('player_bonuses', 'ck_player_bonuses_status', "status IN ('active','completed','expired','forfeited')"),
]     # (table, constraint name, expression): ENUM values and the MySQL CHECKs
for table, name, expr in CHECKS:
    spark.sql(f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({expr})")
print(f"{len(CHECKS)} CHECK constraints added (enforced on every write)")

KEY_CONSTRAINTS = [
    'ALTER TABLE affiliates ADD CONSTRAINT pk_affiliates PRIMARY KEY (affiliate_id)',
    'ALTER TABLE players ADD CONSTRAINT pk_players PRIMARY KEY (player_id)',
    'ALTER TABLE player_identity ADD CONSTRAINT pk_player_identity PRIMARY KEY (player_id)',
    'ALTER TABLE player_vip_tier_history ADD CONSTRAINT pk_player_vip_tier_history PRIMARY KEY (player_id, valid_from_utc)',
    'ALTER TABLE player_tag_history ADD CONSTRAINT pk_player_tag_history PRIMARY KEY (tag_history_id)',
    'ALTER TABLE wallets ADD CONSTRAINT pk_wallets PRIMARY KEY (wallet_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT pk_wallet_transactions PRIMARY KEY (wallet_txn_id)',
    'ALTER TABLE payment_methods ADD CONSTRAINT pk_payment_methods PRIMARY KEY (method_id)',
    'ALTER TABLE deposit_attempts ADD CONSTRAINT pk_deposit_attempts PRIMARY KEY (deposit_attempt_id)',
    'ALTER TABLE withdrawal_requests ADD CONSTRAINT pk_withdrawal_requests PRIMARY KEY (withdrawal_id)',
    'ALTER TABLE bets ADD CONSTRAINT pk_bets PRIMARY KEY (bet_id)',
    'ALTER TABLE sports_events ADD CONSTRAINT pk_sports_events PRIMARY KEY (event_id)',
    'ALTER TABLE sports_bet_details ADD CONSTRAINT pk_sports_bet_details PRIMARY KEY (bet_id)',
    'ALTER TABLE bet_legs ADD CONSTRAINT pk_bet_legs PRIMARY KEY (leg_id)',
    'ALTER TABLE game_providers ADD CONSTRAINT pk_game_providers PRIMARY KEY (provider_id)',
    'ALTER TABLE games ADD CONSTRAINT pk_games PRIMARY KEY (game_id)',
    'ALTER TABLE casino_round_details ADD CONSTRAINT pk_casino_round_details PRIMARY KEY (bet_id)',
    'ALTER TABLE retail_locations ADD CONSTRAINT pk_retail_locations PRIMARY KEY (location_id)',
    'ALTER TABLE devices ADD CONSTRAINT pk_devices PRIMARY KEY (device_id)',
    'ALTER TABLE retail_bet_details ADD CONSTRAINT pk_retail_bet_details PRIMARY KEY (bet_id)',
    'ALTER TABLE bonus_campaigns ADD CONSTRAINT pk_bonus_campaigns PRIMARY KEY (campaign_id)',
    'ALTER TABLE player_bonuses ADD CONSTRAINT pk_player_bonuses PRIMARY KEY (player_bonus_id)',
    'ALTER TABLE bonus_rollover_events ADD CONSTRAINT pk_bonus_rollover_events PRIMARY KEY (rollover_event_id)',
    'ALTER TABLE players ADD CONSTRAINT fk_players_affiliate FOREIGN KEY (affiliate_id) REFERENCES affiliates (affiliate_id)',
    'ALTER TABLE player_identity ADD CONSTRAINT fk_identity_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE player_vip_tier_history ADD CONSTRAINT fk_viphist_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE player_tag_history ADD CONSTRAINT fk_taghist_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE wallets ADD CONSTRAINT fk_wallet_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (wallet_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_reversal FOREIGN KEY (reversal_of_wallet_txn_id) REFERENCES wallet_transactions (wallet_txn_id)',
    'ALTER TABLE deposit_attempts ADD CONSTRAINT fk_deposit_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE deposit_attempts ADD CONSTRAINT fk_deposit_method FOREIGN KEY (method_id) REFERENCES payment_methods (method_id)',
    'ALTER TABLE withdrawal_requests ADD CONSTRAINT fk_withdrawal_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE withdrawal_requests ADD CONSTRAINT fk_withdrawal_method FOREIGN KEY (method_id) REFERENCES payment_methods (method_id)',
    'ALTER TABLE bets ADD CONSTRAINT fk_bets_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE sports_bet_details ADD CONSTRAINT fk_sportsdet_bet FOREIGN KEY (bet_id) REFERENCES bets (bet_id)',
    'ALTER TABLE bet_legs ADD CONSTRAINT fk_leg_bet FOREIGN KEY (bet_id) REFERENCES bets (bet_id)',
    'ALTER TABLE bet_legs ADD CONSTRAINT fk_leg_event FOREIGN KEY (event_id) REFERENCES sports_events (event_id)',
    'ALTER TABLE games ADD CONSTRAINT fk_games_provider FOREIGN KEY (provider_id) REFERENCES game_providers (provider_id)',
    'ALTER TABLE casino_round_details ADD CONSTRAINT fk_casinodet_bet FOREIGN KEY (bet_id) REFERENCES bets (bet_id)',
    'ALTER TABLE casino_round_details ADD CONSTRAINT fk_casinodet_game FOREIGN KEY (game_id) REFERENCES games (game_id)',
    'ALTER TABLE retail_bet_details ADD CONSTRAINT fk_retaildet_bet FOREIGN KEY (bet_id) REFERENCES bets (bet_id)',
    'ALTER TABLE retail_bet_details ADD CONSTRAINT fk_retaildet_loc FOREIGN KEY (location_id) REFERENCES retail_locations (location_id)',
    'ALTER TABLE retail_bet_details ADD CONSTRAINT fk_retaildet_device FOREIGN KEY (device_id) REFERENCES devices (device_id)',
    'ALTER TABLE player_bonuses ADD CONSTRAINT fk_pbonus_player FOREIGN KEY (player_id) REFERENCES players (player_id)',
    'ALTER TABLE player_bonuses ADD CONSTRAINT fk_pbonus_campaign FOREIGN KEY (campaign_id) REFERENCES bonus_campaigns (campaign_id)',
    'ALTER TABLE bonus_rollover_events ADD CONSTRAINT fk_rollover_pbonus FOREIGN KEY (player_bonus_id) REFERENCES player_bonuses (player_bonus_id)',
    'ALTER TABLE bonus_rollover_events ADD CONSTRAINT fk_rollover_bet FOREIGN KEY (bet_id) REFERENCES bets (bet_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_deposit FOREIGN KEY (related_deposit_attempt_id) REFERENCES deposit_attempts (deposit_attempt_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_withdrawal FOREIGN KEY (related_withdrawal_id) REFERENCES withdrawal_requests (withdrawal_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_bet FOREIGN KEY (related_bet_id) REFERENCES bets (bet_id)',
    'ALTER TABLE wallet_transactions ADD CONSTRAINT fk_wtxn_bonus FOREIGN KEY (related_player_bonus_id) REFERENCES player_bonuses (player_bonus_id)',
]   # ALTER TABLE ... PRIMARY KEY / FOREIGN KEY (parents first)
if ON_DATABRICKS:
    for stmt in KEY_CONSTRAINTS:
        spark.sql(stmt)
    print(f"{len(KEY_CONSTRAINTS)} primary and foreign keys declared in Unity Catalog (informational)")
else:
    print(f"local run: {len(KEY_CONSTRAINTS)} PK/FK declarations skipped (Unity Catalog only)")

# COMMAND ----------

# MAGIC %md ## 3. Seed data (the same rows as `seed.sql`)

# COMMAND ----------

SEED = [
    "INSERT INTO affiliates (affiliate_id, affiliate_code, name, traffic_source) VALUES (1,'AFF-001','Windhoek Sports Blog','affiliate'), (2,'AFF-002','Direct','organic')",
    "INSERT INTO players (player_id, registered_at_utc, kyc_status, vip_tier, status, traffic_source, affiliate_id, preferred_currency) VALUES (1,'2026-08-01 08:00:00','verified','gold','active','affiliate',1,'NAD'), (2,'2026-08-15 09:30:00','verified','standard','active','organic',2,'NAD'), (3,'2026-08-20 12:00:00','verified','standard','active','organic',2,'NAD')",
    "INSERT INTO player_identity (player_id, first_name, last_name, date_of_birth, national_id_number, email, phone, address_city, address_country) VALUES (1,'Anna','Shikongo','1990-04-12', 'ENC[demo-only]', 'anna.s@example.com','+264811000001','Windhoek','NA'), (2,'Johan','Beukes','1985-11-03', 'ENC[demo-only]', 'johan.b@example.com','+264811000002','Windhoek','NA'), (3,'Maria','Nangolo','1992-02-27','ENC[demo-only]', 'maria.n@example.com','+264811000003','Swakopmund','NA')",
    "INSERT INTO player_vip_tier_history (player_id, vip_tier, valid_from_utc, valid_to_utc, changed_by) VALUES (1,'standard','2026-08-01 08:00:00','2026-09-01 00:00:00','system:tier_rule'), (1,'gold','2026-09-01 00:00:00',NULL,'system:tier_rule'), (2,'standard','2026-08-15 09:30:00',NULL,'system:tier_rule'), (3,'standard','2026-08-20 12:00:00',NULL,'system:tier_rule')",
    "INSERT INTO player_tag_history (player_id, tag, valid_from_utc, valid_to_utc) VALUES (1,'high_value','2026-09-01 00:00:00',NULL), (3,'bonus_abuse_watch','2026-09-05 00:00:00',NULL)",
    "INSERT INTO wallets (wallet_id, player_id, currency, real_balance, bonus_balance) VALUES (1,1,'NAD', 1190.00, 0.00), (2,2,'NAD', 400.00, 0.00), (3,3,'NAD', 100.00, 30.00)",
    "INSERT INTO payment_methods (method_id, method_code, rail_family) VALUES (1,'EFT_INSTANT','EFT'), (2,'VOUCHER','voucher')",
    "INSERT INTO deposit_attempts (deposit_attempt_id, player_id, method_id, amount, currency, gateway_ref, status, created_at_utc, settled_at_utc) VALUES (1,2,1,500.00,'NAD','GW-D0001','failed','2026-09-10 09:00:00',NULL), (2,2,1,500.00,'NAD','GW-D0002','success','2026-09-10 09:04:00','2026-09-10 09:05:00'), (3,1,1,1000.00,'NAD','GW-D0003','success','2026-09-02 10:00:00','2026-09-02 10:01:00'), (4,3,1,100.00,'NAD','GW-D0004','success','2026-09-03 11:00:00','2026-09-03 11:01:00')",
    "INSERT INTO wallet_transactions (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction, balance_before, balance_after, related_deposit_attempt_id, idempotency_key, created_at_utc) VALUES (1,2,2,'deposit','real',500.00,'credit',0,500.00,2,'deposit:GW-D0002','2026-09-10 09:05:00'), (2,1,1,'deposit','real',1000.00,'credit',0,1000.00,3,'deposit:GW-D0003','2026-09-02 10:01:00'), (3,3,3,'deposit','real',100.00,'credit',0,100.00,4,'deposit:GW-D0004','2026-09-03 11:01:00')",
    "INSERT INTO bonus_campaigns (campaign_id, name, campaign_type, trigger_rule, audience_rule, rollover_multiple, min_odds, expiry_days, valid_from_utc) VALUES (1,'Registration Bonus','registration','first_deposit','all_new_players',3.00,1.500,30,'2026-01-01 00:00:00')",
    "INSERT INTO player_bonuses (player_bonus_id, player_id, campaign_id, granted_amount, rollover_required, rollover_progress, status, granted_at_utc, expires_at_utc, resolved_at_utc) VALUES (1,3,1,50.00,150.00,60.00,'active','2026-09-03 11:05:00','2026-10-03 11:05:00',NULL), (2,2,1,25.00,75.00,75.00,'completed','2026-09-15 09:05:00','2026-10-15 09:05:00','2026-09-20 10:00:00')",
    "INSERT INTO wallet_transactions (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction, balance_before, balance_after, related_player_bonus_id, idempotency_key, created_at_utc) VALUES (4,3,3,'bonus_credit','bonus',50.00,'credit',0,50.00,1,'bonus_grant:1','2026-09-03 11:05:00')",
    "INSERT INTO sports_events (event_id, sport, league, home_team, away_team, starts_at_utc) VALUES (1,'Football','Namibia Premier League','Blue Waters','African Stars','2026-09-05 15:00:00')",
    "INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, status, payout_amount, placed_at_utc, settled_at_utc) VALUES (1,'REQ-BET-0001',1,'sportsbook','web',200.00,0.00,'won',360.00,'2026-09-05 14:00:00','2026-09-05 17:00:00'), (2,'REQ-BET-0002',3,'sportsbook','app',0.00,20.00,'lost',0.00,'2026-09-06 10:00:00','2026-09-06 12:00:00')",
    "INSERT INTO sports_bet_details (bet_id, bet_class, total_odds, leg_count, min_odds_rule_applied) VALUES (1,'single',1.800,1,NULL), (2,'single',2.000,1,1.500)",
    "INSERT INTO bet_legs (bet_id, event_id, market, selection, odds, leg_result) VALUES (1,1,'match_winner','Blue Waters',1.800,'won'), (2,1,'match_winner','African Stars',2.000,'lost')",
    "INSERT INTO wallet_transactions (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction, balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc) VALUES (5,1,1,'bet_stake','real',200.00,'debit',1000.00,800.00,1,'bet_stake:1','2026-09-05 14:00:00'), (6,1,1,'bet_win','real',360.00,'credit',800.00,1160.00,1,'bet_win:1','2026-09-05 17:00:00'), (7,3,3,'bet_stake','bonus',20.00,'debit',50.00,30.00,2,'bet_stake:2','2026-09-06 10:00:00')",
    "INSERT INTO bonus_rollover_events (player_bonus_id, bet_id, contribution_amount, created_at_utc) VALUES (1,2,20.00,'2026-09-06 12:00:00')",
    "INSERT INTO game_providers (provider_id, name) VALUES (1,'Pragmatic Play')",
    "INSERT INTO games (game_id, provider_id, name, category, rtp_theoretical) VALUES (1,1,'Gates of Olympus','slots',96.500)",
    "INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, status, payout_amount, placed_at_utc, settled_at_utc) VALUES (3,'REQ-BET-0003',1,'casino','app',50.00,0.00,'won',80.00,'2026-09-07 20:00:00','2026-09-07 20:00:05')",
    "INSERT INTO casino_round_details (bet_id, game_id, provider_round_ref) VALUES (3,1,'PP-ROUND-000123')",
    "INSERT INTO wallet_transactions (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction, balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc) VALUES (8,1,1,'bet_stake','real',50.00,'debit',1160.00,1110.00,3,'bet_stake:3','2026-09-07 20:00:00'), (9,1,1,'bet_win','real',80.00,'credit',1110.00,1190.00,3,'bet_win:3','2026-09-07 20:00:05')",
    "INSERT INTO retail_locations (location_id, name, address_city) VALUES (1,'JSB Retail - Independence Ave','Windhoek')",
    "INSERT INTO devices (device_id, fingerprint, device_type) VALUES (1,'POS-TERM-0007','pos_terminal')",
    "INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount, stake_bonus_amount, status, payout_amount, placed_at_utc, settled_at_utc) VALUES (4,'REQ-BET-0004',2,'retail','retail',100.00,0.00,'lost',0.00,'2026-09-11 13:00:00','2026-09-11 16:00:00')",
    "INSERT INTO retail_bet_details (bet_id, location_id, device_id, ticket_number) VALUES (4,1,1,'TCK-000456')",
    "INSERT INTO wallet_transactions (wallet_txn_id, wallet_id, player_id, txn_type, balance_type, amount, direction, balance_before, balance_after, related_bet_id, idempotency_key, created_at_utc) VALUES (10,2,2,'bet_stake','real',100.00,'debit',500.00,400.00,4,'bet_stake:4','2026-09-11 13:00:00')",
]
for stmt in SEED:
    spark.sql(stmt)
display(spark.sql("""SELECT 'players' AS t, COUNT(*) AS n FROM players UNION ALL SELECT 'bets', COUNT(*) FROM bets
                     UNION ALL SELECT 'wallet_transactions', COUNT(*) FROM wallet_transactions
                     UNION ALL SELECT 'player_bonuses', COUNT(*) FROM player_bonuses"""))

# COMMAND ----------

# MAGIC %md ## 4. Delta enforces CHECK constraints: a negative stake is refused

# COMMAND ----------

try:
    spark.sql("""INSERT INTO bets (bet_id, request_id, player_id, product, channel, stake_real_amount,
                 stake_bonus_amount, status, payout_amount, placed_at_utc)
                 VALUES (99, 'REQ-BAD', 1, 'casino', 'app', -5, 0, 'open', 0, current_timestamp())""")
    refused = False
except Exception as e:  # noqa: BLE001
    refused = "CHECK" in str(e).upper() or "constraint" in str(e).lower()
    print("refused:", str(e).splitlines()[0][:160])
check(refused, "a negative stake violates ck_bets_stake_nonneg and is rejected")

# COMMAND ----------

# MAGIC %md ## 5. Duplicate-free: every primary key and natural key; referential integrity: every foreign key

# COMMAND ----------

KEYS = [
    ('affiliates', ['affiliate_code'], 'unique'),
    ('affiliates', ['affiliate_id'], 'primary key'),
    ('players', ['player_id'], 'primary key'),
    ('player_identity', ['email'], 'unique'),
    ('player_identity', ['player_id'], 'primary key'),
    ('player_vip_tier_history', ['player_id', 'valid_from_utc'], 'primary key'),
    ('player_tag_history', ['player_id', 'tag', 'valid_from_utc'], 'unique'),
    ('player_tag_history', ['tag_history_id'], 'primary key'),
    ('wallets', ['player_id', 'currency'], 'unique'),
    ('wallets', ['wallet_id'], 'primary key'),
    ('wallet_transactions', ['idempotency_key'], 'unique'),
    ('wallet_transactions', ['wallet_txn_id'], 'primary key'),
    ('payment_methods', ['method_code'], 'unique'),
    ('payment_methods', ['method_id'], 'primary key'),
    ('deposit_attempts', ['gateway_ref'], 'unique'),
    ('deposit_attempts', ['deposit_attempt_id'], 'primary key'),
    ('withdrawal_requests', ['request_id'], 'unique'),
    ('withdrawal_requests', ['withdrawal_id'], 'primary key'),
    ('bets', ['request_id'], 'unique'),
    ('bets', ['bet_id'], 'primary key'),
    ('sports_events', ['sport', 'league', 'home_team', 'away_team', 'starts_at_utc'], 'unique'),
    ('sports_events', ['event_id'], 'primary key'),
    ('sports_bet_details', ['bet_id'], 'primary key'),
    ('bet_legs', ['bet_id', 'event_id', 'market'], 'unique'),
    ('bet_legs', ['leg_id'], 'primary key'),
    ('game_providers', ['name'], 'unique'),
    ('game_providers', ['provider_id'], 'primary key'),
    ('games', ['provider_id', 'name'], 'unique'),
    ('games', ['game_id'], 'primary key'),
    ('casino_round_details', ['game_id', 'provider_round_ref'], 'unique'),
    ('casino_round_details', ['bet_id'], 'primary key'),
    ('retail_locations', ['name', 'address_city'], 'unique'),
    ('retail_locations', ['location_id'], 'primary key'),
    ('devices', ['fingerprint'], 'unique'),
    ('devices', ['device_id'], 'primary key'),
    ('retail_bet_details', ['location_id', 'ticket_number'], 'unique'),
    ('retail_bet_details', ['bet_id'], 'primary key'),
    ('bonus_campaigns', ['name', 'valid_from_utc'], 'unique'),
    ('bonus_campaigns', ['campaign_id'], 'primary key'),
    ('player_bonuses', ['player_bonus_id'], 'primary key'),
    ('bonus_rollover_events', ['player_bonus_id', 'bet_id'], 'unique'),
    ('bonus_rollover_events', ['rollover_event_id'], 'primary key'),
]            # (table, [columns], 'primary key' | 'unique')
FKS = [
    ('players', ['affiliate_id'], 'affiliates', ['affiliate_id']),
    ('player_identity', ['player_id'], 'players', ['player_id']),
    ('player_vip_tier_history', ['player_id'], 'players', ['player_id']),
    ('player_tag_history', ['player_id'], 'players', ['player_id']),
    ('wallets', ['player_id'], 'players', ['player_id']),
    ('wallet_transactions', ['wallet_id'], 'wallets', ['wallet_id']),
    ('wallet_transactions', ['player_id'], 'players', ['player_id']),
    ('wallet_transactions', ['reversal_of_wallet_txn_id'], 'wallet_transactions', ['wallet_txn_id']),
    ('deposit_attempts', ['player_id'], 'players', ['player_id']),
    ('deposit_attempts', ['method_id'], 'payment_methods', ['method_id']),
    ('withdrawal_requests', ['player_id'], 'players', ['player_id']),
    ('withdrawal_requests', ['method_id'], 'payment_methods', ['method_id']),
    ('bets', ['player_id'], 'players', ['player_id']),
    ('sports_bet_details', ['bet_id'], 'bets', ['bet_id']),
    ('bet_legs', ['bet_id'], 'bets', ['bet_id']),
    ('bet_legs', ['event_id'], 'sports_events', ['event_id']),
    ('games', ['provider_id'], 'game_providers', ['provider_id']),
    ('casino_round_details', ['bet_id'], 'bets', ['bet_id']),
    ('casino_round_details', ['game_id'], 'games', ['game_id']),
    ('retail_bet_details', ['bet_id'], 'bets', ['bet_id']),
    ('retail_bet_details', ['location_id'], 'retail_locations', ['location_id']),
    ('retail_bet_details', ['device_id'], 'devices', ['device_id']),
    ('player_bonuses', ['player_id'], 'players', ['player_id']),
    ('player_bonuses', ['campaign_id'], 'bonus_campaigns', ['campaign_id']),
    ('bonus_rollover_events', ['player_bonus_id'], 'player_bonuses', ['player_bonus_id']),
    ('bonus_rollover_events', ['bet_id'], 'bets', ['bet_id']),
    ('wallet_transactions', ['related_deposit_attempt_id'], 'deposit_attempts', ['deposit_attempt_id']),
    ('wallet_transactions', ['related_withdrawal_id'], 'withdrawal_requests', ['withdrawal_id']),
    ('wallet_transactions', ['related_bet_id'], 'bets', ['bet_id']),
    ('wallet_transactions', ['related_player_bonus_id'], 'player_bonuses', ['player_bonus_id']),
]              # (child table, [columns], parent table, [columns])

key_rows = []
for table, cols, kind in KEYS:
    c = ", ".join(cols)
    dupes = spark.sql(f"SELECT COUNT(*) FROM (SELECT {c} FROM {table} GROUP BY {c} HAVING COUNT(*) > 1)").first()[0]
    key_rows.append((table, kind, c, dupes))
fk_rows = []
for child, ccols, parent, pcols in FKS:
    on = " AND ".join(f"c.{a} = p.{b}" for a, b in zip(ccols, pcols))
    notnull = " AND ".join(f"c.{a} IS NOT NULL" for a in ccols)
    orphans = spark.sql(f"SELECT COUNT(*) FROM {child} c LEFT ANTI JOIN {parent} p ON {on} WHERE {notnull}").first()[0]
    fk_rows.append((f"{child}({', '.join(ccols)})", f"{parent}({', '.join(pcols)})", orphans))

display(spark.createDataFrame(key_rows, "table STRING, key STRING, columns STRING, duplicate_keys BIGINT"))
display(spark.createDataFrame(fk_rows, "foreign_key STRING, references STRING, orphan_rows BIGINT"))
check(all(r[3] == 0 for r in key_rows), f"no duplicates on any of the {len(key_rows)} primary and natural keys")
check(all(r[2] == 0 for r in fk_rows), f"no orphans on any of the {len(fk_rows)} foreign keys")

# COMMAND ----------

# MAGIC %md ## 6. The four required queries
# MAGIC Assumption, as in the MySQL version: GGR = stakes − payouts on settled bets, and NGR = GGR − realised bonus cost.

# COMMAND ----------

# MAGIC %md ### (a) NGR by product for a month

# COMMAND ----------

q_a = spark.sql("""
WITH product_ggr AS (
    SELECT product, SUM(stake_real_amount + stake_bonus_amount) AS turnover, SUM(payout_amount) AS payouts,
           SUM(stake_real_amount + stake_bonus_amount) - SUM(payout_amount) AS ggr
    FROM bets
    WHERE settled_at_utc >= '2026-09-01' AND settled_at_utc < '2026-10-01' AND status IN ('won', 'lost')
    GROUP BY product
),
product_bonus_cost AS (
    SELECT b.product, SUM(wt.amount) AS bonus_cost
    FROM wallet_transactions wt JOIN bets b ON b.bet_id = wt.related_bet_id
    WHERE wt.txn_type = 'bet_stake' AND wt.balance_type = 'bonus' AND b.status = 'lost'
      AND b.settled_at_utc >= '2026-09-01' AND b.settled_at_utc < '2026-10-01'
    GROUP BY b.product
)
SELECT g.product, g.turnover, g.payouts, g.ggr, COALESCE(c.bonus_cost, 0) AS bonus_cost,
       g.ggr - COALESCE(c.bonus_cost, 0) AS ngr
FROM product_ggr g LEFT JOIN product_bonus_cost c ON c.product = g.product
ORDER BY g.product""")
display(q_a)
ngr = {r["product"]: float(r["ngr"]) for r in q_a.collect()}
check(ngr == {"casino": -30.0, "retail": 100.0, "sportsbook": -160.0}, "NGR: casino -30, retail 100, sportsbook -160")

# COMMAND ----------

# MAGIC %md ### (b) Bonus cost as a % of NGR, by campaign

# COMMAND ----------

q_b = spark.sql("""
WITH campaign_cost AS (
    SELECT pb.campaign_id, SUM(pb.granted_amount) AS bonus_cost
    FROM player_bonuses pb
    WHERE pb.status IN ('completed', 'expired', 'forfeited')
      AND pb.resolved_at_utc >= '2026-09-01' AND pb.resolved_at_utc < '2026-10-01'
    GROUP BY pb.campaign_id
),
period_ggr AS (
    SELECT SUM(stake_real_amount + stake_bonus_amount) - SUM(payout_amount) AS total_ggr
    FROM bets WHERE settled_at_utc >= '2026-09-01' AND settled_at_utc < '2026-10-01' AND status IN ('won', 'lost')
),
period_bonus_cost AS (
    SELECT SUM(wt.amount) AS total_bonus_cost
    FROM wallet_transactions wt JOIN bets b ON b.bet_id = wt.related_bet_id
    WHERE wt.txn_type = 'bet_stake' AND wt.balance_type = 'bonus' AND b.status = 'lost'
      AND b.settled_at_utc >= '2026-09-01' AND b.settled_at_utc < '2026-10-01'
),
period_ngr AS (
    SELECT (SELECT total_ggr FROM period_ggr) - COALESCE((SELECT total_bonus_cost FROM period_bonus_cost), 0) AS total_ngr
)
SELECT bc.name AS campaign, cc.bonus_cost,
       ROUND(100 * cc.bonus_cost / NULLIF((SELECT total_ngr FROM period_ngr), 0), 2) AS bonus_cost_pct_of_ngr
FROM campaign_cost cc JOIN bonus_campaigns bc ON bc.campaign_id = cc.campaign_id""")
display(q_b)
r = q_b.first()
check(r["campaign"] == "Registration Bonus" and float(r["bonus_cost_pct_of_ngr"]) == -27.78,
      "Registration Bonus cost is -27.78% of NGR")

# COMMAND ----------

# MAGIC %md ### (c) A player's balance at a given date and time (from the ledger)

# COMMAND ----------

PLAYER_ID, AS_OF = 1, "2026-09-06 00:00:00"
q_c = spark.sql(f"""
SELECT balance_type, SUM(CASE WHEN direction = 'credit' THEN amount ELSE -amount END) AS balance_as_of
FROM wallet_transactions
WHERE player_id = {PLAYER_ID} AND created_at_utc <= '{AS_OF}' AND status = 'posted'
GROUP BY balance_type""")
display(q_c)
check([(r[0], float(r[1])) for r in q_c.collect()] == [("real", 1160.0)], "player 1 real balance on 2026-09-06 is 1,160.00")

# COMMAND ----------

# MAGIC %md ### (d) Deposits that failed, then the player succeeded later

# COMMAND ----------

q_d = spark.sql("""
SELECT f.player_id, f.deposit_attempt_id AS failed_attempt_id, f.created_at_utc AS failed_at,
       s.deposit_attempt_id AS succeeded_attempt_id, s.created_at_utc AS succeeded_at,
       timestampdiff(MINUTE, f.created_at_utc, s.created_at_utc) AS minutes_to_success, s.amount AS succeeded_amount
FROM deposit_attempts f
JOIN deposit_attempts s
  ON s.player_id = f.player_id AND s.status = 'success'
 AND s.created_at_utc > f.created_at_utc AND s.created_at_utc <= f.created_at_utc + INTERVAL 24 HOURS
WHERE f.status = 'failed'
  AND NOT EXISTS (SELECT 1 FROM deposit_attempts s2
                  WHERE s2.player_id = f.player_id AND s2.status = 'success'
                    AND s2.created_at_utc > f.created_at_utc AND s2.created_at_utc < s.created_at_utc)
ORDER BY f.created_at_utc""")
display(q_d)
rows = q_d.collect()
check(len(rows) == 1 and rows[0]["player_id"] == 2 and rows[0]["minutes_to_success"] == 4,
      "player 2 failed, then succeeded 4 minutes later")

# COMMAND ----------

# MAGIC %md ## 7. The wallet balance cache equals the ledger

# COMMAND ----------

drift = spark.sql("""
SELECT w.wallet_id, w.real_balance, w.bonus_balance, l.real_ledger, l.bonus_ledger
FROM wallets w
LEFT JOIN (SELECT wallet_id,
                  SUM(CASE WHEN balance_type = 'real' THEN CASE WHEN direction = 'credit' THEN amount ELSE -amount END ELSE 0 END) AS real_ledger,
                  SUM(CASE WHEN balance_type = 'bonus' THEN CASE WHEN direction = 'credit' THEN amount ELSE -amount END ELSE 0 END) AS bonus_ledger
           FROM wallet_transactions WHERE status = 'posted' GROUP BY wallet_id) l ON l.wallet_id = w.wallet_id
WHERE w.real_balance <> COALESCE(l.real_ledger, 0) OR w.bonus_balance <> COALESCE(l.bonus_ledger, 0)""")
check(drift.count() == 0, "every wallet's cached balance equals the sum of its ledger")
